import "@oomol-lab/connector";

declare module "@oomol-lab/connector" {
  interface ActionRegistry {
    /** Create a business, consumer, or government customer in Altoviz. */
    "altoviz.create_customer": {
      input: {
        /** Whether the customer is active. */
        active?: boolean;
        /** The customer type. */
        type?: "Business" | "Consumer" | "Government";
        /** The customer's company name. */
        companyName?: string | null;
        /** The customer's first name. */
        firstName?: string | null;
        /** The customer's last name. */
        lastName?: string | null;
        /**
         * The customer's email address.
         * @format email
         */
        email?: string | null;
        /** The customer ID from an external system. */
        internalId?: string | null;
        /** Internal notes about the customer. */
        internalNotes?: string | null;
        /** The customer number. */
        number?: string | null;
        /** The customer's phone number. */
        phone?: string | null;
        /** The customer's mobile phone number. */
        cellPhone?: string | null;
        /** The customer's title. */
        title?: string | null;
      };
      output: {
        /** An Altoviz customer record. */
        customer: {
          /** The Altoviz customer ID. */
          id?: number;
          /** Whether the customer is active. */
          active?: boolean;
          /** The customer type. */
          type?: "Business" | "Consumer" | "Government";
          /** The display name generated by Altoviz. */
          name?: string | null;
          /** The customer's company name. */
          companyName?: string | null;
          /** The customer's first name. */
          firstName?: string | null;
          /** The customer's last name. */
          lastName?: string | null;
          /** The customer's email address. */
          email?: string | null;
          /** The customer ID from an external system. */
          internalId?: string | null;
          /** The customer number. */
          number?: string | null;
          [key: string]: unknown;
        };
      };
    };
    /** Find Altoviz customers by email, external-system ID, or customer number. */
    "altoviz.find_customers": {
      input: {
        /**
         * The exact customer email to find.
         * @minLength 1
         */
        email?: string;
        /**
         * The customer identifier from an external system.
         * @minLength 1
         */
        internalId?: string;
        /**
         * The Altoviz customer number to find.
         * @minLength 1
         */
        number?: string;
      };
      output: {
        /** The matching Altoviz customers. */
        customers: Array<{
          /** The Altoviz customer ID. */
          id?: number;
          /** Whether the customer is active. */
          active?: boolean;
          /** The customer type. */
          type?: "Business" | "Consumer" | "Government";
          /** The display name generated by Altoviz. */
          name?: string | null;
          /** The customer's company name. */
          companyName?: string | null;
          /** The customer's first name. */
          firstName?: string | null;
          /** The customer's last name. */
          lastName?: string | null;
          /** The customer's email address. */
          email?: string | null;
          /** The customer ID from an external system. */
          internalId?: string | null;
          /** The customer number. */
          number?: string | null;
          [key: string]: unknown;
        }>;
      };
    };
    /** Retrieve one Altoviz customer by its numeric customer ID. */
    "altoviz.get_customer": {
      input: {
        /**
         * The numeric Altoviz customer ID.
         * @exclusiveMinimum 0
         */
        customerId: number;
      };
      output: {
        /** An Altoviz customer record. */
        customer: {
          /** The Altoviz customer ID. */
          id?: number;
          /** Whether the customer is active. */
          active?: boolean;
          /** The customer type. */
          type?: "Business" | "Consumer" | "Government";
          /** The display name generated by Altoviz. */
          name?: string | null;
          /** The customer's company name. */
          companyName?: string | null;
          /** The customer's first name. */
          firstName?: string | null;
          /** The customer's last name. */
          lastName?: string | null;
          /** The customer's email address. */
          email?: string | null;
          /** The customer ID from an external system. */
          internalId?: string | null;
          /** The customer number. */
          number?: string | null;
          [key: string]: unknown;
        };
      };
    };
    /** List Altoviz customers with full-text search, ordering, and stable pagination metadata. */
    "altoviz.list_customers": {
      input: {
        /**
         * The one-based page index.
         * @minimum 1
         * @default 1
         */
        pageIndex?: number;
        /**
         * The number of customers per page.
         * @minimum 1
         * @maximum 100
         * @default 10
         */
        pageSize?: number;
        /**
         * The Altoviz customer field ordering expression.
         * @minLength 1
         */
        orderBy?: string;
        /**
         * A full-text customer search query.
         * @minLength 1
         */
        query?: string;
      };
      output: {
        /** The customers on the current page. */
        customers: Array<{
          /** The Altoviz customer ID. */
          id?: number;
          /** Whether the customer is active. */
          active?: boolean;
          /** The customer type. */
          type?: "Business" | "Consumer" | "Government";
          /** The display name generated by Altoviz. */
          name?: string | null;
          /** The customer's company name. */
          companyName?: string | null;
          /** The customer's first name. */
          firstName?: string | null;
          /** The customer's last name. */
          lastName?: string | null;
          /** The customer's email address. */
          email?: string | null;
          /** The customer ID from an external system. */
          internalId?: string | null;
          /** The customer number. */
          number?: string | null;
          [key: string]: unknown;
        }>;
        /** Pagination metadata returned in Altoviz response headers. */
        pagination: {
          /** The current one-based page index. */
          pageIndex: number;
          /** The requested page size. */
          pageSize: number;
          /** The total number of pages when supplied by Altoviz. */
          pageCount?: number;
          /** The total number of matching records when supplied by Altoviz. */
          recordCount?: number;
          /** The relative URL of the next page. */
          next?: string;
          /** The relative URL of the previous page. */
          previous?: string;
        };
      };
    };
  }
}
