import "@oomol-lab/connector";

declare module "@oomol-lab/connector" {
  interface ActionRegistry {
    /** Count input tokens for an Anthropic message request. */
    "anthropic.count_message_tokens": {
      input: {
        /** The Anthropic model identifier to use. */
        model: string;
        /**
         * The ordered conversation history to count.
         * @minItems 1
         */
        messages: Array<{
          /** The role of the message author. */
          role?: "user" | "assistant";
          /** Anthropic message content. */
          content?: string | Array<Record<string, unknown>>;
          [key: string]: unknown;
        }>;
        /** System prompt content. */
        system?: string | Array<Record<string, unknown>>;
        /** A JSON object passed through to the Anthropic API. */
        thinking?: Record<string, unknown>;
        /** Tool selection strategy for the request. */
        tool_choice?: "auto" | "any" | "none" | Record<string, unknown>;
        /** Tools available to the model. */
        tools?: Array<Record<string, unknown>>;
        [key: string]: unknown;
      };
      output: {
        /** The number of input tokens counted for the request. */
        input_tokens?: number;
        [key: string]: unknown;
      };
    };
    /** Create a non-streaming Anthropic message. */
    "anthropic.create_message": {
      input: {
        /** The Anthropic model identifier to use. */
        model: string;
        /**
         * The maximum number of tokens to generate.
         * @minimum 1
         */
        max_tokens: number;
        /**
         * The ordered conversation history sent to the model.
         * @minItems 1
         */
        messages: Array<{
          /** The role of the message author. */
          role?: "user" | "assistant";
          /** Anthropic message content. */
          content?: string | Array<Record<string, unknown>>;
          [key: string]: unknown;
        }>;
        /** System prompt content. */
        system?: string | Array<Record<string, unknown>>;
        /** Metadata about the request. */
        metadata?: {
          /** An external user identifier for abuse detection. */
          user_id?: string;
          [key: string]: unknown;
        };
        /** Custom text sequences that stop generation. */
        stop_sequences?: Array<string>;
        /** Whether to request a streaming response. This connector only accepts false or an omitted value. */
        stream?: boolean;
        /**
         * The sampling temperature.
         * @minimum 0
         * @maximum 1
         */
        temperature?: number;
        /** A JSON object passed through to the Anthropic API. */
        thinking?: Record<string, unknown>;
        /** Tool selection strategy for the request. */
        tool_choice?: "auto" | "any" | "none" | Record<string, unknown>;
        /** Tools available to the model. */
        tools?: Array<Record<string, unknown>>;
        /**
         * Only sample from the top K options for each token.
         * @minimum 0
         */
        top_k?: number;
        /**
         * The nucleus sampling threshold.
         * @minimum 0
         * @maximum 1
         */
        top_p?: number;
        [key: string]: unknown;
      };
      output: {
        /** The message identifier. */
        id?: string;
        /** The object type returned by the API. */
        type?: string;
        /** The role of the returned message. */
        role?: string;
        /** The model used to generate the response. */
        model?: string;
        /** Content blocks generated by the model. */
        content?: Array<Record<string, unknown>>;
        /** The reason generation stopped. */
        stop_reason?: string | null;
        /** The stop sequence that ended generation. */
        stop_sequence?: string | null;
        /** Token usage information. */
        usage?: {
          /** The number of input tokens consumed. */
          input_tokens?: number;
          /** The number of output tokens generated. */
          output_tokens?: number;
          [key: string]: unknown;
        };
        [key: string]: unknown;
      };
    };
    /** Fetch metadata for one Anthropic model. */
    "anthropic.get_model": {
      input: {
        /** The exact Anthropic model identifier to retrieve. */
        model_id: string;
      };
      output: {
        /** The model identifier. */
        id?: string;
        /** The object type returned by the API. */
        type?: string;
        /** A human-readable model name. */
        display_name?: string;
        /**
         * The date and time when the model was created.
         * @format date-time
         */
        created_at?: string;
        [key: string]: unknown;
      };
    };
    /** List Anthropic models available to the current API key. */
    "anthropic.list_models": {
      input: {
        /** Returns models before this model identifier. */
        before_id?: string;
        /** Returns models after this model identifier. */
        after_id?: string;
        /**
         * The maximum number of models to return.
         * @minimum 1
         * @maximum 1000
         */
        limit?: number;
      };
      output: {
        /** The list of Anthropic models. */
        data?: Array<{
          /** The model identifier. */
          id?: string;
          /** The object type returned by the API. */
          type?: string;
          /** A human-readable model name. */
          display_name?: string;
          /**
           * The date and time when the model was created.
           * @format date-time
           */
          created_at?: string;
          [key: string]: unknown;
        }>;
        /** Whether more results are available. */
        has_more?: boolean;
        /** The first model identifier in this page. */
        first_id?: string | null;
        /** The last model identifier in this page. */
        last_id?: string | null;
        [key: string]: unknown;
      };
    };
  }
}
