import "@oomol-lab/connector";

declare module "@oomol-lab/connector" {
  interface ActionRegistry {
    /** Get detailed Crypto APIs market data for one asset by its Crypto APIs reference ID. */
    "crypto_apis.get_asset_details_by_id": {
      input: {
        /**
         * The unique Crypto APIs reference ID for the asset.
         * @minLength 1
         */
        assetId: string;
        /** A client-provided context value returned by Crypto APIs to correlate responses with requests. */
        context?: string;
      };
      output: {
        /**
         * The Crypto APIs REST API version that handled the request.
         * @minLength 1
         */
        apiVersion: string;
        /**
         * The unique request ID generated by Crypto APIs.
         * @minLength 1
         */
        requestId: string;
        /** A client-provided context value returned by Crypto APIs to correlate responses with requests. */
        context?: string;
        /** Detailed Crypto APIs market data for one asset. */
        item: {
          /** The latest USD-denominated market rate returned for an asset. */
          latestRate?: {
            /**
             * The latest rate amount.
             * @minLength 1
             */
            amount: string;
            /** The UNIX timestamp when Crypto APIs calculated the latest rate. */
            calculationTimestamp?: number;
            /**
             * The unit of the latest asset price.
             * @minLength 1
             */
            unit: string;
          };
          /** Encoded asset logo data returned by Crypto APIs. */
          logo?: {
            /**
             * The encoding of the image data, usually base64.
             * @minLength 1
             */
            encoding: string;
            /**
             * The encoded image data.
             * @minLength 1
             */
            imageData: string;
            /**
             * The MIME type of the encoded logo image.
             * @minLength 1
             */
            mimeType: string;
          };
          /**
           * The asset name.
           * @minLength 1
           */
          name: string;
          /**
           * The asset symbol as introduced by its founders.
           * @minLength 1
           */
          originalSymbol: string;
          /**
           * The unique Crypto APIs reference ID for the asset.
           * @minLength 1
           */
          referenceId: string;
          /**
           * The asset slug in Crypto APIs listings.
           * @minLength 1
           */
          slug?: string;
          /** Provider-specific market data for the asset. */
          specificData?: Record<string, unknown>;
          /**
           * The unique asset symbol in Crypto APIs listings.
           * @minLength 1
           */
          symbol: string;
          /** The supported asset type. */
          type: "fiat" | "crypto";
          [key: string]: unknown;
        };
      };
    };
    /** Get detailed Crypto APIs market data for one asset by its asset symbol. */
    "crypto_apis.get_asset_details_by_symbol": {
      input: {
        /**
         * The asset symbol in Crypto APIs listings.
         * @minLength 1
         */
        assetSymbol: string;
        /** A client-provided context value returned by Crypto APIs to correlate responses with requests. */
        context?: string;
      };
      output: {
        /**
         * The Crypto APIs REST API version that handled the request.
         * @minLength 1
         */
        apiVersion: string;
        /**
         * The unique request ID generated by Crypto APIs.
         * @minLength 1
         */
        requestId: string;
        /** A client-provided context value returned by Crypto APIs to correlate responses with requests. */
        context?: string;
        /** Detailed Crypto APIs market data for one asset. */
        item: {
          /** The latest USD-denominated market rate returned for an asset. */
          latestRate?: {
            /**
             * The latest rate amount.
             * @minLength 1
             */
            amount: string;
            /** The UNIX timestamp when Crypto APIs calculated the latest rate. */
            calculationTimestamp?: number;
            /**
             * The unit of the latest asset price.
             * @minLength 1
             */
            unit: string;
          };
          /** Encoded asset logo data returned by Crypto APIs. */
          logo?: {
            /**
             * The encoding of the image data, usually base64.
             * @minLength 1
             */
            encoding: string;
            /**
             * The encoded image data.
             * @minLength 1
             */
            imageData: string;
            /**
             * The MIME type of the encoded logo image.
             * @minLength 1
             */
            mimeType: string;
          };
          /**
           * The asset name.
           * @minLength 1
           */
          name: string;
          /**
           * The asset symbol as introduced by its founders.
           * @minLength 1
           */
          originalSymbol: string;
          /**
           * The unique Crypto APIs reference ID for the asset.
           * @minLength 1
           */
          referenceId: string;
          /**
           * The asset slug in Crypto APIs listings.
           * @minLength 1
           */
          slug?: string;
          /** Provider-specific market data for the asset. */
          specificData?: Record<string, unknown>;
          /**
           * The unique asset symbol in Crypto APIs listings.
           * @minLength 1
           */
          symbol: string;
          /** The supported asset type. */
          type: "fiat" | "crypto";
          [key: string]: unknown;
        };
      };
    };
    /** Get the exchange rate for one Crypto APIs asset reference ID versus another asset reference ID. */
    "crypto_apis.get_exchange_rate_by_asset_ids": {
      input: {
        /**
         * The base asset reference ID to get a rate for.
         * @minLength 1
         */
        fromAssetId: string;
        /**
         * The relation asset reference ID in which the base asset rate is displayed.
         * @minLength 1
         */
        toAssetId: string;
        /** A client-provided context value returned by Crypto APIs to correlate responses with requests. */
        context?: string;
        /** The optional UNIX timestamp for historical market data used to calculate the exchange rate. Crypto APIs supports up to 30 days back. */
        calculationTimestamp?: number;
      };
      output: {
        /**
         * The Crypto APIs REST API version that handled the request.
         * @minLength 1
         */
        apiVersion: string;
        /**
         * The unique request ID generated by Crypto APIs.
         * @minLength 1
         */
        requestId: string;
        /** A client-provided context value returned by Crypto APIs to correlate responses with requests. */
        context?: string;
        /** A Crypto APIs exchange rate between two assets. */
        item: {
          /** The UNIX timestamp for the market data used to calculate the rate. */
          calculationTimestamp: number;
          /**
           * The base asset reference ID.
           * @minLength 1
           */
          fromAssetId: string;
          /**
           * The base asset symbol.
           * @minLength 1
           */
          fromAssetSymbol: string;
          /**
           * The exchange rate between assets calculated from weighted recent exchange trades.
           * @minLength 1
           */
          rate: string;
          /**
           * The relation asset reference ID.
           * @minLength 1
           */
          toAssetId: string;
          /**
           * The relation asset symbol.
           * @minLength 1
           */
          toAssetSymbol: string;
        };
      };
    };
    /** Get the exchange rate for one asset symbol versus another asset symbol from Crypto APIs. */
    "crypto_apis.get_exchange_rate_by_symbols": {
      input: {
        /**
         * The base asset symbol to get a rate for.
         * @minLength 1
         */
        fromAssetSymbol: string;
        /**
         * The relation asset symbol in which the base asset rate is displayed.
         * @minLength 1
         */
        toAssetSymbol: string;
        /** A client-provided context value returned by Crypto APIs to correlate responses with requests. */
        context?: string;
        /** The optional UNIX timestamp for historical market data used to calculate the exchange rate. Crypto APIs supports up to 30 days back. */
        calculationTimestamp?: number;
      };
      output: {
        /**
         * The Crypto APIs REST API version that handled the request.
         * @minLength 1
         */
        apiVersion: string;
        /**
         * The unique request ID generated by Crypto APIs.
         * @minLength 1
         */
        requestId: string;
        /** A client-provided context value returned by Crypto APIs to correlate responses with requests. */
        context?: string;
        /** A Crypto APIs exchange rate between two assets. */
        item: {
          /** The UNIX timestamp for the market data used to calculate the rate. */
          calculationTimestamp: number;
          /**
           * The base asset reference ID.
           * @minLength 1
           */
          fromAssetId: string;
          /**
           * The base asset symbol.
           * @minLength 1
           */
          fromAssetSymbol: string;
          /**
           * The exchange rate between assets calculated from weighted recent exchange trades.
           * @minLength 1
           */
          rate: string;
          /**
           * The relation asset reference ID.
           * @minLength 1
           */
          toAssetId: string;
          /**
           * The relation asset symbol.
           * @minLength 1
           */
          toAssetSymbol: string;
        };
      };
    };
    /** List fiat and cryptocurrency assets supported by Crypto APIs market data endpoints. */
    "crypto_apis.list_supported_assets": {
      input: {
        /** A client-provided context value returned by Crypto APIs to correlate responses with requests. */
        context?: string;
        /**
         * The number of assets to return per page.
         * @minimum 0
         */
        limit?: number;
        /**
         * The starting index for returned assets.
         * @minimum 0
         */
        offset?: number;
        /** The supported asset type. */
        type?: "fiat" | "crypto";
      };
      output: {
        /**
         * The Crypto APIs REST API version that handled the request.
         * @minLength 1
         */
        apiVersion: string;
        /**
         * The unique request ID generated by Crypto APIs.
         * @minLength 1
         */
        requestId: string;
        /** A client-provided context value returned by Crypto APIs to correlate responses with requests. */
        context?: string;
        /** The number of items requested per page. */
        limit: number;
        /** The starting index of returned items. */
        offset: number;
        /** The total number of supported assets matching the request. */
        total: number;
        /** The supported assets on this page. */
        items: Array<{
          /**
           * The asset name.
           * @minLength 1
           */
          name: string;
          /**
           * The asset symbol as introduced by its founders.
           * @minLength 1
           */
          originalSymbol: string;
          /**
           * The unique Crypto APIs reference ID for the asset.
           * @minLength 1
           */
          referenceId: string;
          /**
           * The unique asset symbol in Crypto APIs listings.
           * @minLength 1
           */
          symbol: string;
          /** The supported asset type. */
          type: "fiat" | "crypto";
        }>;
      };
    };
  }
}
