import "@oomol-lab/connector";

declare module "@oomol-lab/connector" {
  interface ActionRegistry {
    /** Create a new FFHub FFmpeg transcoding task from a full FFmpeg command or argument-only command string. */
    "ffhub.create_ffmpeg_task": {
      input: {
        /**
         * Full FFmpeg command or argument-only command string accepted by FFHub, including remote input URLs and output file names.
         * @minLength 1
         */
        command: string;
        /**
         * Optional callback URL that receives the same payload as `get_ffmpeg_task`.
         * @format uri
         */
        webhook?: string;
        /** Whether FFHub should collect ffprobe metadata for generated output files. */
        withMetadata?: boolean;
      };
      output: {
        /** Created FFHub task ID. */
        taskId: string;
      };
    };
    /** Get the current status, timing, error, and output files for one FFHub FFmpeg task. */
    "ffhub.get_ffmpeg_task": {
      input: {
        /**
         * FFHub task ID to retrieve.
         * @minLength 1
         */
        taskId: string;
      };
      output: {
        /** Normalized FFHub task detail. */
        task: {
          /** FFHub task ID. */
          taskId: string;
          /** FFHub customer identifier when returned. */
          userId: string | null;
          /** FFHub task status. */
          status: "pending" | "running" | "completed" | "failed";
          /** Task progress percentage when returned. */
          progress: number | null;
          /** Task error message when the task failed. */
          error: string | null;
          /** Worker execution time in seconds when returned. */
          elapsed: string | null;
          /** Total elapsed time from creation to completion in seconds when returned. */
          totalElapsed: string | null;
          /** Task creation timestamp. */
          createdAt: string | null;
          /** Task completion timestamp, or null when pending. */
          finishedAt: string | null;
          /** Output files generated by the task. */
          outputs: Array<{
            /** Output file name. */
            filename: string;
            /** Output file URL. */
            url: string;
            /** Output file size in bytes when available. */
            size: number | null;
            /** Raw ffprobe metadata object returned by FFHub when requested. */
            metadata: Record<string, unknown> | null;
          }>;
        };
      };
    };
    /** List FFHub FFmpeg tasks with optional customer, status, limit, and offset filters. */
    "ffhub.list_ffmpeg_tasks": {
      input: {
        /**
         * Optional FFHub customer identifier.
         * @minLength 1
         */
        userId?: string;
        /** FFHub task status. */
        status?: "pending" | "running" | "completed" | "failed";
        /**
         * Maximum number of tasks to return, from 1 to 100.
         * @minimum 1
         * @maximum 100
         */
        limit?: number;
        /**
         * Number of tasks to skip before reading the current page.
         * @minimum 0
         */
        offset?: number;
      };
      output: {
        /** Normalized FFHub tasks. */
        tasks: Array<{
          /** FFHub task ID. */
          taskId: string;
          /** FFHub customer identifier when returned. */
          userId: string | null;
          /** FFHub task status. */
          status: "pending" | "running" | "completed" | "failed";
          /** Task progress percentage when returned. */
          progress: number | null;
          /** Task error message when the task failed. */
          error: string | null;
          /** Worker execution time in seconds when returned. */
          elapsed: string | null;
          /** Total elapsed time from creation to completion in seconds when returned. */
          totalElapsed: string | null;
          /** Task creation timestamp. */
          createdAt: string | null;
          /** Task completion timestamp, or null when pending. */
          finishedAt: string | null;
          /** Output files generated by the task. */
          outputs: Array<{
            /** Output file name. */
            filename: string;
            /** Output file URL. */
            url: string;
            /** Output file size in bytes when available. */
            size: number | null;
            /** Raw ffprobe metadata object returned by FFHub when requested. */
            metadata: Record<string, unknown> | null;
          }>;
        }>;
        /**
         * Total number of matching FFHub tasks.
         * @minimum 0
         */
        total: number;
      };
    };
  }
}
