import "@oomol-lab/connector";

declare module "@oomol-lab/connector" {
  interface ActionRegistry {
    /** Generate speech audio with CosyVoice TTS. */
    "fusion-api.cosyvoice_tts_generate": {
      input: (unknown) & (unknown);
      output: Record<string, unknown>;
    };
    /** Get cphone-nano-banana task result */
    "fusion-api.cphone_nano_banana_result": {
      input: {
        /**
         * Session ID
         * @example "01936c8e-7890-7abc-def0-123456789abc"
         */
        sessionID: string;
        [key: string]: unknown;
      };
      output: {
        /** Task state. */
        state: "completed";
        /** Task result data. */
        data: Record<string, unknown>;
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "processing";
        /** Task progress. */
        progress: number;
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "not_found";
        /** Error message. */
        error: string;
        [key: string]: unknown;
      };
    };
    /** Get cphone-nano-banana task state */
    "fusion-api.cphone_nano_banana_state": {
      input: {
        /**
         * Session ID
         * @example "01936c8e-7890-7abc-def0-123456789abc"
         */
        sessionID: string;
        [key: string]: unknown;
      };
      output: {
        /** Task state. */
        state: "completed";
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "processing";
        /** Task progress. */
        progress: number;
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "not_found";
        /** Error message. */
        error: string;
        [key: string]: unknown;
      };
    };
    /** Edit images with Nano Banana */
    "fusion-api.cphone_nano_banana_submit": {
      input: {
        /**
         * Text prompt for image generation or editing
         * @minLength 1
         * @example "A beautiful landscape painting"
         */
        prompt: string;
        /**
         * Model name to use, defaults to gemini-2.5-flash-image-preview
         * @default "gemini-2.5-flash-image-preview"
         * @example "nano-banana-2"
         */
        model?: "nano-banana-2" | "nano-banana-2-2k" | "nano-banana-2-4k" | "gemini-3-pro-image-preview" | "gemini-2.5-flash-image" | "nano-banana-hd" | "nano-banana" | "gemini-2.5-flash-image-preview" | "nano-banana-pro" | "nano-banana-pro-4k";
        /**
         * Generated image aspect ratio
         * @example "1:1"
         */
        aspectRatio?: "21:9" | "1:1" | "4:3" | "3:2" | "2:3" | "5:4" | "4:5" | "3:4" | "16:9" | "9:16";
        /**
         * List of reference image URLs for image-to-image generation or editing
         * @minItems 1
         * @example ["https://example.com/ref.png"]
         */
        imageURLs?: Array<string>;
        /**
         * Generated image resolution, only supported by nano-banana-2
         * @example "1K"
         */
        imageSize?: "1K" | "2K" | "4K";
        [key: string]: unknown;
      };
      output: {
        /** Task session ID. */
        sessionId: string;
        [key: string]: unknown;
      };
    };
    /** Recognize text from a single image. */
    "fusion-api.deepseek_ocr_recognize": {
      input: {
        /**
         * Publicly accessible URL of the image to recognize.
         * @minLength 1
         * @format uri
         * @example "https://example.com/page.png"
         */
        imageURL: string;
        /**
         * Custom OCR prompt.
         * @minLength 1
         * @example "Extract all text from this page as Markdown."
         */
        prompt?: string;
        /**
         * Optional OOMOL API key that overrides the default key for this request.
         * @minLength 1
         * @example "sk-xxx"
         */
        oomolApiKey?: string;
        [key: string]: unknown;
      };
      output: {
        /** Recognized OCR text. */
        text: string;
        /**
         * Number of input tokens used by the request.
         * @minimum 0
         */
        inputTokens?: number;
        /**
         * Number of output tokens generated by the request.
         * @minimum 0
         */
        outputTokens?: number;
        /**
         * Total number of tokens used by the request.
         * @minimum 0
         */
        totalTokens?: number;
        /** Model used for OCR recognition. */
        model?: string;
        [key: string]: unknown;
      };
    };
    /** Get doubao-stt task result */
    "fusion-api.doubao_stt_result": {
      input: {
        /**
         * Session ID
         * @example "01936c8e-7890-7abc-def0-123456789abc"
         */
        sessionID: string;
        [key: string]: unknown;
      };
      output: {
        /** Task state. */
        state: "completed";
        /** Task result data. */
        data: Record<string, unknown>;
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "processing";
        /** Task progress. */
        progress: number;
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "not_found";
        /** Error message. */
        error: string;
        [key: string]: unknown;
      };
    };
    /** Get doubao-stt task state */
    "fusion-api.doubao_stt_state": {
      input: {
        /**
         * Session ID
         * @example "01936c8e-7890-7abc-def0-123456789abc"
         */
        sessionID: string;
        [key: string]: unknown;
      };
      output: {
        /** Task state. */
        state: "completed";
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "processing";
        /** Task progress. */
        progress: number;
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "not_found";
        /** Error message. */
        error: string;
        [key: string]: unknown;
      };
    };
    /** Convert speech to text with Doubao */
    "fusion-api.doubao_stt_submit": {
      input: {
        /**
         * Publicly accessible URL of the audio file to recognize
         * @minLength 1
         * @example "https://example.com/audio.mp3"
         */
        audioURL: string;
        /**
         * Audio container format, supporting raw, wav, mp3, and ogg
         * @minLength 1
         * @example "mp3"
         */
        format: string;
        [key: string]: unknown;
      };
      output: {
        /** Task session ID. */
        sessionId: string;
        [key: string]: unknown;
      };
    };
    /** Generate images from text with Doubao Seedream */
    "fusion-api.doubao_text_to_image_seedream_generate": {
      input: {
        /**
         * Text prompt for image generation
         * @minLength 1
         * @maxLength 1000
         * @example "一只在星空下奔跑的白色独角兽"
         */
        prompt: string;
        /**
         * Reference image URL or Base64 encoding for image-to-image generation
         * @example "https://example.com/reference.jpg"
         */
        image?: string;
        /**
         * Image size, supporting descriptive sizes (1K/2K/4K) or explicit width and height in pixels
         * @default "2048x2048"
         */
        size?: "1K" | "2K" | "4K" | "1k" | "2k" | "4k" | {
          /**
           * Image width in pixels
           * @exclusiveMinimum 0
           * @example 2048
           */
          width: number;
          /**
           * Image height in pixels
           * @exclusiveMinimum 0
           * @example 2048
           */
          height: number;
          [key: string]: unknown;
        };
        /**
         * Whether to enable multi-image generation mode; auto lets the model decide
         * @default "disabled"
         * @example "disabled"
         */
        multiple?: "disabled" | "auto";
        /**
         * Maximum number of images to generate in one request, only effective in multi-image mode
         * @minimum 1
         * @maximum 15
         * @default 1
         * @example 1
         */
        maxCount?: number;
        /**
         * Whether to add a watermark
         * @default true
         * @example true
         */
        watermark?: boolean;
        /**
         * Generation mode: standard prioritizes quality, fast prioritizes speed
         * @default "standard"
         * @example "standard"
         */
        optionsnew?: "standard" | "fast";
        [key: string]: unknown;
      };
      output: Record<string, unknown>;
    };
    /** Get doubao-tts task result */
    "fusion-api.doubao_tts_result": {
      input: {
        /**
         * Session ID
         * @example "01936c8e-7890-7abc-def0-123456789abc"
         */
        sessionID: string;
        [key: string]: unknown;
      };
      output: {
        /** Task state. */
        state: "completed";
        /** Task result data. */
        data: Record<string, unknown>;
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "processing";
        /** Task progress. */
        progress: number;
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "not_found";
        /** Error message. */
        error: string;
        [key: string]: unknown;
      };
    };
    /** Get doubao-tts task state */
    "fusion-api.doubao_tts_state": {
      input: {
        /**
         * Session ID
         * @example "01936c8e-7890-7abc-def0-123456789abc"
         */
        sessionID: string;
        [key: string]: unknown;
      };
      output: {
        /** Task state. */
        state: "completed";
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "processing";
        /** Task progress. */
        progress: number;
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "not_found";
        /** Error message. */
        error: string;
        [key: string]: unknown;
      };
    };
    /** Convert text to speech with Doubao */
    "fusion-api.doubao_tts_submit": {
      input: {
        /**
         * Text content to synthesize into speech, up to 100,000 characters
         * @minLength 1
         * @example "你好，欢迎使用豆包语音合成服务。"
         */
        text: string;
        /**
         * Speaker ID specifying the voice used for synthesized audio
         * @minLength 1
         * @example "zh_female_vv_uranus_bigtts"
         */
        voice: string;
        [key: string]: unknown;
      };
      output: {
        /** Task session ID. */
        sessionId: string;
        [key: string]: unknown;
      };
    };
    /** Get fal-aura-sr task result */
    "fusion-api.fal_aura_sr_result": {
      input: {
        /**
         * Session ID
         * @example "01936c8e-7890-7abc-def0-123456789abc"
         */
        sessionID: string;
        [key: string]: unknown;
      };
      output: {
        /** Task state. */
        state: "completed";
        /** Task result data. */
        data: Record<string, unknown>;
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "processing";
        /** Task progress. */
        progress: number;
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "not_found";
        /** Error message. */
        error: string;
        [key: string]: unknown;
      };
    };
    /** Get fal-aura-sr task state */
    "fusion-api.fal_aura_sr_state": {
      input: {
        /**
         * Session ID
         * @example "01936c8e-7890-7abc-def0-123456789abc"
         */
        sessionID: string;
        [key: string]: unknown;
      };
      output: {
        /** Task state. */
        state: "completed";
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "processing";
        /** Task progress. */
        progress: number;
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "not_found";
        /** Error message. */
        error: string;
        [key: string]: unknown;
      };
    };
    /** Image super-resolution upscaling */
    "fusion-api.fal_aura_sr_submit": {
      input: {
        /**
         * URL of the image to upscale with super resolution
         * @minLength 1
         * @example "https://example.com/low-res-image.png"
         */
        imageURL: string;
        [key: string]: unknown;
      };
      output: {
        /** Task session ID. */
        sessionId: string;
        [key: string]: unknown;
      };
    };
    /** Get fal-nano-banana-2 task result */
    "fusion-api.fal_nano_banana_2_result": {
      input: {
        /**
         * Session ID
         * @example "01936c8e-7890-7abc-def0-123456789abc"
         */
        sessionID: string;
        [key: string]: unknown;
      };
      output: {
        /** Task state. */
        state: "completed";
        /** Task result data. */
        data: Record<string, unknown>;
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "processing";
        /** Task progress. */
        progress: number;
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "not_found";
        /** Error message. */
        error: string;
        [key: string]: unknown;
      };
    };
    /** Get fal-nano-banana-2 task state */
    "fusion-api.fal_nano_banana_2_state": {
      input: {
        /**
         * Session ID
         * @example "01936c8e-7890-7abc-def0-123456789abc"
         */
        sessionID: string;
        [key: string]: unknown;
      };
      output: {
        /** Task state. */
        state: "completed";
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "processing";
        /** Task progress. */
        progress: number;
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "not_found";
        /** Error message. */
        error: string;
        [key: string]: unknown;
      };
    };
    /** Generate or edit images with Nano Banana 2 */
    "fusion-api.fal_nano_banana_2_submit": {
      input: {
        /**
         * Text prompt for image generation or editing
         * @minLength 1
         * @example "A vibrant cyberpunk cityscape at dusk"
         */
        prompt: string;
        /**
         * List of reference image URLs for image-to-image generation or editing
         * @minItems 1
         * @maxItems 14
         * @example ["https://example.com/reference-image.png"]
         */
        imageURLs?: Array<string>;
        /**
         * Number of images to generate
         * @minimum 1
         * @maximum 4
         * @default 1
         * @example 1
         */
        numImages?: number;
        /**
         * Generated image aspect ratio
         * @default "auto"
         * @example "auto"
         */
        aspectRatio?: "auto" | "21:9" | "16:9" | "3:2" | "4:3" | "5:4" | "1:1" | "4:5" | "3:4" | "2:3" | "9:16";
        /**
         * Output image file format
         * @default "png"
         * @example "png"
         */
        outputFormat?: "jpeg" | "png" | "webp";
        /**
         * Content safety tolerance level, where 1 is the strictest and 6 is the loosest
         * @default "4"
         * @example "4"
         */
        safetyTolerance?: "1" | "2" | "3" | "4" | "5" | "6";
        /**
         * Random seed used to reproduce results with the same input
         * @example 42
         */
        seed?: number;
        /**
         * Generated image resolution
         * @default "1K"
         * @example "1K"
         */
        resolution?: "0.5K" | "1K" | "2K" | "4K";
        /**
         * Whether to restrict each prompt round to a single valid result
         * @default true
         * @example true
         */
        limitGenerations?: boolean;
        /**
         * Whether to enable web-search-enhanced generation
         * @example false
         */
        enableWebSearch?: boolean;
        [key: string]: unknown;
      };
      output: {
        /** Task session ID. */
        sessionId: string;
        [key: string]: unknown;
      };
    };
    /** Get fal-nano-banana-pro task result */
    "fusion-api.fal_nano_banana_pro_result": {
      input: {
        /**
         * Session ID
         * @example "01936c8e-7890-7abc-def0-123456789abc"
         */
        sessionID: string;
        [key: string]: unknown;
      };
      output: {
        /** Task state. */
        state: "completed";
        /** Task result data. */
        data: Record<string, unknown>;
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "processing";
        /** Task progress. */
        progress: number;
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "not_found";
        /** Error message. */
        error: string;
        [key: string]: unknown;
      };
    };
    /** Get fal-nano-banana-pro task state */
    "fusion-api.fal_nano_banana_pro_state": {
      input: {
        /**
         * Session ID
         * @example "01936c8e-7890-7abc-def0-123456789abc"
         */
        sessionID: string;
        [key: string]: unknown;
      };
      output: {
        /** Task state. */
        state: "completed";
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "processing";
        /** Task progress. */
        progress: number;
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "not_found";
        /** Error message. */
        error: string;
        [key: string]: unknown;
      };
    };
    /** Edit images with Nano Banana Pro */
    "fusion-api.fal_nano_banana_pro_submit": {
      input: {
        /**
         * Text prompt for image generation or editing
         * @minLength 1
         * @example "A futuristic cityscape at night"
         */
        prompt: string;
        /**
         * List of reference image URLs for image-to-image generation or editing
         * @maxItems 3
         * @example ["https://example.com/ref.png"]
         */
        imageUrls?: Array<string>;
        /**
         * Generated image aspect ratio
         * @default "1:1"
         * @example "1:1"
         */
        aspectRatio?: "21:9" | "16:9" | "3:2" | "4:3" | "5:4" | "1:1" | "4:5" | "3:4" | "2:3" | "9:16";
        /**
         * Output image file format
         * @default "png"
         * @example "png"
         */
        outputFormat?: "png" | "jpeg" | "webp" | "jpg";
        /**
         * Generated image resolution
         * @default "1K"
         * @example "1K"
         */
        resolution?: "1K" | "2K" | "4K";
        /**
         * Number of images to generate
         * @minimum 1
         * @maximum 8
         * @default 1
         * @example 1
         */
        numImages?: number;
        [key: string]: unknown;
      };
      output: {
        /** Task session ID. */
        sessionId: string;
        [key: string]: unknown;
      };
    };
    /** Get fal-nano-banana task result */
    "fusion-api.fal_nano_banana_result": {
      input: {
        /**
         * Session ID
         * @example "01936c8e-7890-7abc-def0-123456789abc"
         */
        sessionID: string;
        [key: string]: unknown;
      };
      output: {
        /** Task state. */
        state: "completed";
        /** Task result data. */
        data: Record<string, unknown>;
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "processing";
        /** Task progress. */
        progress: number;
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "not_found";
        /** Error message. */
        error: string;
        [key: string]: unknown;
      };
    };
    /** Get fal-nano-banana task state */
    "fusion-api.fal_nano_banana_state": {
      input: {
        /**
         * Session ID
         * @example "01936c8e-7890-7abc-def0-123456789abc"
         */
        sessionID: string;
        [key: string]: unknown;
      };
      output: {
        /** Task state. */
        state: "completed";
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "processing";
        /** Task progress. */
        progress: number;
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "not_found";
        /** Error message. */
        error: string;
        [key: string]: unknown;
      };
    };
    /** Edit images with Nano Banana */
    "fusion-api.fal_nano_banana_submit": {
      input: {
        /**
         * Text prompt for image generation or editing
         * @minLength 1
         * @example "A beautiful landscape painting"
         */
        prompt: string;
        /**
         * List of reference image URLs for image-to-image generation or editing
         * @minItems 1
         * @example ["https://example.com/ref.png"]
         */
        imageURLs?: Array<string>;
        /**
         * Number of images to generate
         * @minimum 1
         * @example 1
         */
        numImages?: number;
        /**
         * Output image file format
         * @example "png"
         */
        outputFormat?: "jpeg" | "png" | "webp";
        /**
         * Generated image aspect ratio
         * @example "1:1"
         */
        aspectRatio?: "21:9" | "1:1" | "4:3" | "3:2" | "2:3" | "5:4" | "4:5" | "3:4" | "16:9" | "9:16";
        [key: string]: unknown;
      };
      output: {
        /** Task session ID. */
        sessionId: string;
        [key: string]: unknown;
      };
    };
    /** Image with background removed */
    "fusion-api.fal_remove_background_result": {
      input: {
        /**
         * Session ID
         * @example "01936c8e-7890-7abc-def0-123456789abc"
         */
        sessionID: string;
        [key: string]: unknown;
      };
      output: {
        /** Information about the image after background removal */
        image: {
          /**
           * URL of the image after background removal
           * @example "https://fal.media/files/output/abc123.png"
           */
          url: string;
          /**
           * Image MIME type
           * @example "image/png"
           */
          content_type: string;
          /** Output filename */
          file_name: string | null;
          /** File size in bytes */
          file_size: number | null;
          /**
           * Image width in pixels
           * @example 1024
           */
          width: number;
          /**
           * Image height in pixels
           * @example 768
           */
          height: number;
          [key: string]: unknown;
        };
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "processing";
        /** Task progress. */
        progress: number;
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "not_found";
        /** Error message. */
        error: string;
        [key: string]: unknown;
      };
    };
    /** Get fal-remove-background task state */
    "fusion-api.fal_remove_background_state": {
      input: {
        /**
         * Session ID
         * @example "01936c8e-7890-7abc-def0-123456789abc"
         */
        sessionID: string;
        [key: string]: unknown;
      };
      output: {
        /** Task state. */
        state: "completed";
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "processing";
        /** Task progress. */
        progress: number;
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "not_found";
        /** Error message. */
        error: string;
        [key: string]: unknown;
      };
    };
    /** Remove image backgrounds with the Fal.ai BRIA model */
    "fusion-api.fal_remove_background_submit": {
      input: {
        /**
         * URL of the image whose background should be removed
         * @minLength 1
         * @example "https://example.com/photo.jpg"
         */
        imageURL: string;
        [key: string]: unknown;
      };
      output: {
        /** Task session ID. */
        sessionId: string;
        [key: string]: unknown;
      };
    };
    /** Abort multipart upload */
    "fusion-api.file_upload_abort_multipart_upload": {
      input: {
        /**
         * Multipart upload ID to abort
         * @minLength 1
         * @example "upload-abc123"
         */
        uploadID: string;
        /**
         * Storage path of the S3 object
         * @minLength 1
         * @example "file-upload/user-id/file-id/photo.png"
         */
        key: string;
        [key: string]: unknown;
      };
      output: Record<string, unknown>;
    };
    /** Complete multipart upload */
    "fusion-api.file_upload_complete_multipart_upload": {
      input: {
        /**
         * Multipart upload ID
         * @minLength 1
         * @example "upload-abc123"
         */
        uploadID: string;
        /**
         * Storage path of the S3 object
         * @minLength 1
         * @example "file-upload/user-id/file-id/photo.png"
         */
        key: string;
        /**
         * List of uploaded part information
         * @maxItems 10000
         * @example [{"partNumber":1,"etag":"\"abc123\""}]
         */
        parts: Array<{
          /**
           * Part number
           * @minimum 1
           * @maximum 10000
           * @example 1
           */
          partNumber: number;
          /**
           * ETag value of the part
           * @minLength 1
           * @example "\"abc123def456\""
           */
          etag: string;
          [key: string]: unknown;
        }>;
        [key: string]: unknown;
      };
      output: Record<string, unknown>;
    };
    /** Initialize multipart upload */
    "fusion-api.file_upload_create_multipart_upload": {
      input: {
        /**
         * File suffix, mutually exclusive with filename
         * @minLength 1
         * @example "png"
         */
        fileSuffix?: string;
        /**
         * Full filename, mutually exclusive with fileSuffix and preferred when provided
         * @minLength 1
         * @example "photo.png"
         */
        filename?: string;
        /**
         * File size in bytes, up to 500 MB
         * @minimum 1
         * @maximum 524288000
         * @example 10485760
         */
        fileSize: number;
        [key: string]: unknown;
      };
      output: Record<string, unknown>;
    };
    /** Generate a presigned URL for file upload */
    "fusion-api.file_upload_generate_presigned_url": {
      input: {
        /**
         * File suffix, mutually exclusive with filename
         * @minLength 1
         * @example "png"
         */
        fileSuffix?: string;
        /**
         * Full filename, mutually exclusive with fileSuffix and preferred when provided
         * @minLength 1
         * @example "photo.png"
         */
        filename?: string;
        [key: string]: unknown;
      };
      output: Record<string, unknown>;
    };
    /** Generate a presigned URL for multipart upload parts */
    "fusion-api.file_upload_generate_presigned_urls": {
      input: {
        /**
         * Multipart upload ID
         * @minLength 1
         * @example "upload-abc123"
         */
        uploadID: string;
        /**
         * Storage path of the S3 object
         * @minLength 1
         * @example "file-upload/user-id/file-id/photo.png"
         */
        key: string;
        /**
         * List of part numbers for which to generate presigned URLs
         * @maxItems 10000
         * @example [1,2,3]
         */
        partNumbers: Array<number>;
        [key: string]: unknown;
      };
      output: Record<string, unknown>;
    };
    /** Read and extract URL content */
    "fusion-api.jina_reader_read": {
      input: {
        /**
         * Webpage URL whose content should be fetched
         * @example "https://example.com/article"
         */
        URL: string;
        /**
         * Output content format
         * @example "markdown"
         */
        format?: "markdown" | "html" | "text" | "screenshot" | "pageshot";
        /**
         * Rendering engine type: direct for static fetching and browser for dynamic rendering
         * @example "browser"
         */
        engine?: "direct" | "browser" | "cf-browser-rendering";
        /**
         * Whether to return the result in JSON format
         * @example true
         */
        jsonResponse?: boolean;
        /**
         * Page load wait timeout in seconds
         * @example 30
         */
        timeout?: number;
        /**
         * Maximum number of tokens to return
         * @example 2000
         */
        tokenLimit?: number;
        /**
         * Whether to use the ReaderLM-v2 model for HTML-to-Markdown conversion
         * @example false
         */
        useReaderLMV2?: boolean;
        /**
         * Only extract content matching this CSS selector
         * @example "article, .main-content"
         */
        selectorOnly?: string;
        /**
         * Wait for the element matching this CSS selector before extraction
         * @example ".dynamic-list"
         */
        selectorWait?: string;
        /**
         * Remove elements matching this CSS selector before extraction
         * @example "nav, footer, .ads"
         */
        selectorNone?: string;
        /**
         * Whether to remove all images from the output
         * @example true
         */
        removeAllImages?: boolean;
        /**
         * Generate a link summary section at the end; true includes only button links, all includes every link
         * @example "true"
         */
        withLinkSummary?: "true" | "all";
        /**
         * Generate an image summary section at the end
         * @example "true"
         */
        withImageSummary?: "true" | "all";
        [key: string]: unknown;
      };
      output: Record<string, unknown>;
    };
    /** Search web content */
    "fusion-api.jina_reader_search": {
      input: {
        /**
         * Search query keywords
         * @minLength 1
         * @example "2024 年诺贝尔物理学奖获得者"
         */
        content: string;
        /**
         * Search engine type
         * @example "direct"
         */
        engine?: "direct";
        /**
         * Whether to return search results in JSON format
         * @example true
         */
        jsonResponse?: boolean;
        /**
         * Whether to include website icons in the result
         * @example true
         */
        withFavicons?: boolean;
        /**
         * Restrict the geographic location of search results using an ISO country code
         * @example "US"
         */
        googleLocal?: "US" | "CA" | "MX" | "GB" | "DE" | "FR" | "GP" | "CN" | "IN" | "BR" | "AU" | "RU" | "IT" | "ES" | "KR" | "NL" | "CH" | "SE" | "IE" | "SG" | "IL" | "SA" | "AE" | "ZA";
        /**
         * Preferred language for search results
         * @example "en"
         */
        hostLanguage?: "en" | "es" | "fr" | "de" | "ja" | "zh-cn" | "hi" | "pt" | "it" | "ko" | "nl" | "ar" | "sv" | "iw" | "af" | "ru";
        /**
         * Page number for search results
         * @minimum 1
         * @example 1
         */
        pageIndex?: number;
        /**
         * Whether to bypass cache and fetch the latest result
         * @example false
         */
        noCache?: boolean;
        [key: string]: unknown;
      };
      output: Record<string, unknown>;
    };
    /** Generate speech audio */
    "fusion-api.oomol_tts_ng_generate": {
      input: {
        /**
         * Model name.
         * @default "qwen3-tts-flash"
         * @example "qwen3-tts-flash"
         */
        model?: "qwen3-tts-instruct-flash" | "qwen3-tts-flash" | "qwen3-tts-vc-2026-01-22";
        /**
         * Text content to synthesize into speech.
         * @minLength 1
         * @example "你好，欢迎使用千问语音合成服务。"
         */
        text: string;
        /**
         * Preset voice name or cloned voice ID.
         * @minLength 1
         * @default "Cherry"
         * @example "Cherry"
         */
        voice?: string;
        /**
         * Language type of the text.
         * @example "Auto"
         */
        languageType?: "Auto" | "Chinese" | "English" | "German" | "Italian" | "Portuguese" | "Spanish" | "Japanese" | "Korean" | "French" | "Russian";
        /**
         * Speech performance control instruction, only available for instruct models.
         * @minLength 1
         * @example "Speak faster with an upbeat tone."
         */
        instructions?: string;
        /**
         * Whether to optimize speech performance instructions, only available for instruct models.
         * @example true
         */
        optimizeInstructions?: boolean;
        [key: string]: unknown;
      };
      output: {
        /** Temporary URL of the generated audio */
        audioURL: string;
        /** Expiration time of the audio URL */
        expiresAt?: number;
        [key: string]: unknown;
      };
    };
    /** Get oomol-tts task result */
    "fusion-api.oomol_tts_result": {
      input: {
        /**
         * Session ID
         * @example "01936c8e-7890-7abc-def0-123456789abc"
         */
        sessionID: string;
        [key: string]: unknown;
      };
      output: {
        /** Task state. */
        state: "completed";
        /** Task result data. */
        data: Record<string, unknown>;
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "processing";
        /** Task progress. */
        progress: number;
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "not_found";
        /** Error message. */
        error: string;
        [key: string]: unknown;
      };
    };
    /** Get oomol-tts task state */
    "fusion-api.oomol_tts_state": {
      input: {
        /**
         * Session ID
         * @example "01936c8e-7890-7abc-def0-123456789abc"
         */
        sessionID: string;
        [key: string]: unknown;
      };
      output: {
        /** Task state. */
        state: "completed";
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "processing";
        /** Task progress. */
        progress: number;
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "not_found";
        /** Error message. */
        error: string;
        [key: string]: unknown;
      };
    };
    /** Convert text to audio */
    "fusion-api.oomol_tts_submit": {
      input: {
        /**
         * Text content to synthesize into speech, up to 100,000 characters
         * @minLength 1
         * @example "你好，欢迎使用 OOMOL 语音合成服务。"
         */
        text: string;
        /**
         * Speaker ID specifying the voice used for synthesized audio
         * @minLength 1
         * @example "zh_female_vv_uranus_bigtts"
         */
        voice: string;
        [key: string]: unknown;
      };
      output: {
        /** Task session ID. */
        sessionId: string;
        [key: string]: unknown;
      };
    };
    /** Get asynchronous OpenAI image generation result */
    "fusion-api.openai_image_async_result": {
      input: {
        /**
         * Session ID
         * @example "01936c8e-7890-7abc-def0-123456789abc"
         */
        sessionID: string;
        [key: string]: unknown;
      };
      output: {
        /** Task state. */
        state: "completed";
        /** Task result data. */
        data: Record<string, unknown>;
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "processing";
        /** Task progress. */
        progress: number;
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "not_found";
        /** Error message. */
        error: string;
        [key: string]: unknown;
      };
    };
    /** Submit asynchronous OpenAI image generation requests, including gpt-image-2 image creation. */
    "fusion-api.openai_image_async_submit": {
      input: {
        /**
         * Text prompt for image generation
         * @minLength 1
         * @maxLength 32000
         * @example "A minimalist product photo of a ceramic mug on a walnut table"
         */
        prompt: string;
        /**
         * OpenAI image model name
         * @minLength 1
         * @example "gpt-image-2"
         */
        model?: string;
        /**
         * Background mode
         * @example "auto"
         */
        background?: "transparent" | "opaque" | "auto";
        /**
         * Content moderation strictness
         * @example "auto"
         */
        moderation?: "auto" | "low";
        /**
         * Number of images to generate
         * @minimum 1
         * @maximum 10
         * @example 1
         */
        n?: number;
        /**
         * JPEG or WebP output compression level
         * @minimum 0
         * @maximum 100
         */
        output_compression?: number;
        /**
         * Output image format
         * @example "png"
         */
        output_format?: "png" | "jpeg" | "webp";
        /**
         * Number of partial images for streaming responses
         * @minimum 0
         * @maximum 3
         * @example 2
         */
        partial_images?: number;
        /**
         * Image quality
         * @example "medium"
         */
        quality?: "auto" | "high" | "medium" | "low" | "hd" | "standard";
        /**
         * Output image size. For GPT Image 2, use auto or WIDTHxHEIGHT. Official constraints: largest dimension <= 3840, width and height multiples of 16, longest side at most 3x the shortest side, and total pixels between 655360 and 8294400 inclusive.
         * @pattern ^(auto|[1-9][0-9]*x[1-9][0-9]*)$
         * @example "1536x1152"
         * @example "1024x1024"
         * @example "auto"
         */
        size?: string;
        /**
         * End-user identifier
         * @minLength 1
         * @example "user-123"
         */
        user?: string;
      };
      output: {
        /** Task session ID. */
        sessionId: string;
        [key: string]: unknown;
      };
    };
    /** Get asynchronous OpenAI image edit result */
    "fusion-api.openai_image_edit_async_result": {
      input: {
        /**
         * Session ID
         * @example "01936c8e-7890-7abc-def0-123456789abc"
         */
        sessionID: string;
        [key: string]: unknown;
      };
      output: {
        /** Task state. */
        state: "completed";
        /** Task result data. */
        data: Record<string, unknown>;
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "processing";
        /** Task progress. */
        progress: number;
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "not_found";
        /** Error message. */
        error: string;
        [key: string]: unknown;
      };
    };
    /** Submit asynchronous OpenAI image edit requests, including gpt-image-2 image editing. */
    "fusion-api.openai_image_edit_async_submit": {
      input: {
        /**
         * Text prompt for image editing
         * @minLength 1
         * @maxLength 32000
         * @example "Replace the mug color with matte black and keep everything else unchanged"
         */
        prompt: string;
        /**
         * OpenAI image model name
         * @minLength 1
         * @example "gpt-image-2"
         */
        model?: string;
        /**
         * Background mode
         * @example "auto"
         */
        background?: "transparent" | "opaque" | "auto";
        /**
         * Number of images to generate
         * @minimum 1
         * @maximum 10
         * @example 1
         */
        n?: number;
        /**
         * JPEG or WebP output compression level
         * @minimum 0
         * @maximum 100
         */
        output_compression?: number;
        /**
         * Output image format
         * @example "png"
         */
        output_format?: "png" | "jpeg" | "webp";
        /**
         * Number of partial images for streaming responses
         * @minimum 0
         * @maximum 3
         * @example 2
         */
        partial_images?: number;
        /**
         * Image quality
         * @example "medium"
         */
        quality?: "auto" | "high" | "medium" | "low" | "hd" | "standard";
        /**
         * Output image size. For GPT Image 2, use auto or WIDTHxHEIGHT. Official constraints: largest dimension <= 3840, width and height multiples of 16, longest side at most 3x the shortest side, and total pixels between 655360 and 8294400 inclusive.
         * @pattern ^(auto|[1-9][0-9]*x[1-9][0-9]*)$
         * @example "1536x1152"
         * @example "1024x1024"
         * @example "auto"
         */
        size?: string;
        /**
         * End-user identifier
         * @minLength 1
         * @example "user-123"
         */
        user?: string;
        /**
         * Reference images to edit or compose from
         * @minItems 1
         * @maxItems 16
         * @example [{"image_url":"https://example.com/source.png"}]
         */
        images: Array<Record<string, unknown>>;
        /** Mask image reference for partial edits */
        mask?: Record<string, unknown>;
      };
      output: {
        /** Task session ID. */
        sessionId: string;
        [key: string]: unknown;
      };
    };
    /** Get pdf-transform-epub task result */
    "fusion-api.pdf_transform_epub_result": {
      input: {
        /**
         * Session ID
         * @example "01936c8e-7890-7abc-def0-123456789abc"
         */
        sessionID: string;
        [key: string]: unknown;
      };
      output: {
        /** Task state. */
        state: "completed";
        /** Task result data. */
        data: Record<string, unknown>;
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "processing";
        /** Task progress. */
        progress: number;
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "not_found";
        /** Error message. */
        error: string;
        [key: string]: unknown;
      };
    };
    /** Get pdf-transform-epub task state */
    "fusion-api.pdf_transform_epub_state": {
      input: {
        /**
         * Session ID
         * @example "01936c8e-7890-7abc-def0-123456789abc"
         */
        sessionID: string;
        [key: string]: unknown;
      };
      output: {
        /** Task state. */
        state: "completed";
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "processing";
        /** Task progress. */
        progress: number;
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "not_found";
        /** Error message. */
        error: string;
        [key: string]: unknown;
      };
    };
    /** Convert a PDF to EPUB format */
    "fusion-api.pdf_transform_epub_submit": {
      input: {
        /**
         * Publicly accessible URL of the PDF file to convert
         * @minLength 1
         * @format uri
         * @example "https://example.com/book.pdf"
         */
        pdfURL: string;
        /**
         * OCR model name
         * @default "gundam"
         * @example "gundam"
         */
        model?: "gundam";
        /**
         * Whether to include footnote content
         * @default true
         * @example true
         */
        includesFootnotes?: boolean;
        /**
         * Whether to ignore PDF parsing errors so the whole file can still be output
         * @default true
         * @example true
         */
        ignorePdfErrors?: boolean;
        /**
         * Whether to ignore OCR recognition errors
         * @default true
         * @example true
         */
        ignoreOcrErrors?: boolean;
        /**
         * Number of parallel OCR worker threads
         * @minimum 1
         * @maximum 4
         * @default 1
         * @example 1
         */
        ocrWorkers?: number;
        /**
         * Whether to inline LaTeX formulas into the content
         * @default true
         * @example true
         */
        inlineLatex?: boolean;
        /**
         * OOMOL API key, optionally overriding the default key
         * @example "sk-xxx"
         */
        oomolApiKey?: string;
        /**
         * Output filename, optional
         * @example "my-book"
         */
        filename?: string;
        [key: string]: unknown;
      };
      output: {
        /** Task session ID. */
        sessionId: string;
        [key: string]: unknown;
      };
    };
    /** Get pdf-transform-markdown task result */
    "fusion-api.pdf_transform_markdown_result": {
      input: {
        /**
         * Session ID
         * @example "01936c8e-7890-7abc-def0-123456789abc"
         */
        sessionID: string;
        [key: string]: unknown;
      };
      output: {
        /** Task state. */
        state: "completed";
        /** Task result data. */
        data: Record<string, unknown>;
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "processing";
        /** Task progress. */
        progress: number;
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "not_found";
        /** Error message. */
        error: string;
        [key: string]: unknown;
      };
    };
    /** Get pdf-transform-markdown task state */
    "fusion-api.pdf_transform_markdown_state": {
      input: {
        /**
         * Session ID
         * @example "01936c8e-7890-7abc-def0-123456789abc"
         */
        sessionID: string;
        [key: string]: unknown;
      };
      output: {
        /** Task state. */
        state: "completed";
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "processing";
        /** Task progress. */
        progress: number;
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "not_found";
        /** Error message. */
        error: string;
        [key: string]: unknown;
      };
    };
    /** Convert a PDF to Markdown format */
    "fusion-api.pdf_transform_markdown_submit": {
      input: {
        /**
         * Publicly accessible URL of the PDF file to convert
         * @minLength 1
         * @format uri
         * @example "https://example.com/document.pdf"
         */
        pdfURL: string;
        /**
         * OCR model name
         * @default "gundam"
         * @example "gundam"
         */
        model?: "gundam";
        /**
         * Whether to include footnote content
         * @default true
         * @example true
         */
        includesFootnotes?: boolean;
        /**
         * Whether to ignore PDF parsing errors so the whole file can still be output
         * @default true
         * @example true
         */
        ignorePdfErrors?: boolean;
        /**
         * Whether to ignore OCR recognition errors
         * @default true
         * @example true
         */
        ignoreOcrErrors?: boolean;
        /**
         * Number of parallel OCR worker threads
         * @minimum 1
         * @maximum 4
         * @default 1
         * @example 1
         */
        ocrWorkers?: number;
        /**
         * OOMOL API key, optionally overriding the default key
         * @example "sk-xxx"
         */
        oomolApiKey?: string;
        /**
         * Whether to inline LaTeX formulas into Markdown
         * @default true
         * @example true
         */
        inlineLatex?: boolean;
        /**
         * Output filename, optional
         * @example "my-document"
         */
        filename?: string;
        [key: string]: unknown;
      };
      output: {
        /** Task session ID. */
        sessionId: string;
        [key: string]: unknown;
      };
    };
    /** Get Qwen ASR file transcription task result */
    "fusion-api.qwen_asr_filetrans_result": {
      input: {
        /**
         * Session ID
         * @example "01936c8e-7890-7abc-def0-123456789abc"
         */
        sessionID: string;
        [key: string]: unknown;
      };
      output: {
        /** Task state. */
        state: "completed";
        /** Completed transcription data including taskID, transcriptionURL, usage, and transcription details. */
        data: Record<string, unknown>;
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "processing";
        /** Task progress. */
        progress: number;
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "not_found";
        /** Error message. */
        error: string;
        [key: string]: unknown;
      };
    };
    /** Get Qwen ASR file transcription task state */
    "fusion-api.qwen_asr_filetrans_state": {
      input: {
        /**
         * Session ID
         * @example "01936c8e-7890-7abc-def0-123456789abc"
         */
        sessionID: string;
        [key: string]: unknown;
      };
      output: {
        /** Task state. */
        state: "completed";
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "processing";
        /** Task progress. */
        progress: number;
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "not_found";
        /** Error message. */
        error: string;
        [key: string]: unknown;
      };
    };
    /** Submit a long-audio speech recognition task with Qwen ASR file transcription */
    "fusion-api.qwen_asr_filetrans_submit": {
      input: {
        /**
         * Publicly accessible URL of the audio file to transcribe.
         * @format uri
         * @example "https://example.com/audio.mp3"
         */
        fileURL: string;
        /**
         * Audio language. Leave unspecified when the language is unknown or the audio is multilingual.
         * @example "zh"
         */
        language?: "zh" | "yue" | "en" | "ja" | "de" | "ko" | "ru" | "fr" | "pt" | "ar" | "it" | "es" | "hi" | "id" | "th" | "tr" | "uk" | "vi" | "cs" | "da" | "fil" | "fi" | "is" | "ms" | "no" | "pl" | "sv";
        /**
         * Whether to enable inverse text normalization for Chinese and English audio.
         * @default false
         * @example false
         */
        enableITN?: boolean;
        /**
         * Whether to return word-level timestamps.
         * @default false
         * @example true
         */
        enableWords?: boolean;
        /**
         * Audio channel indexes to transcribe, starting from 0.
         * @minItems 1
         * @default [0]
         * @example [0]
         */
        channelID?: Array<number>;
        [key: string]: unknown;
      };
      output: {
        /** Task session ID. */
        sessionId: string;
        [key: string]: unknown;
      };
    };
    /** Analyze documents with Tongyi Qianwen */
    "fusion-api.qwen_doc_turbo_analyze": {
      input: {
        /**
         * Array of document URLs to process, supporting PDF, Word, Excel, and other formats
         * @minItems 1
         * @maxItems 10
         * @example ["https://example.com/report.pdf"]
         */
        docURLs?: Array<string>;
        /**
         * Document analysis instruction describing the extraction requirements
         * @minLength 1
         * @maxLength 9000
         * @example "提取文档中所有产品型号和对应价格"
         */
        instruction?: string;
        /**
         * Plain text content, mutually exclusive with docURLs mode
         * @minLength 1
         * @maxLength 9000
         * @example "产品 A 价格 100 元，产品 B 价格 200 元"
         */
        text?: string;
        /**
         * System prompt that sets the model role and behavior
         * @default "You are a helpful assistant."
         * @example "You are a helpful assistant."
         */
        systemPrompt?: string;
        /**
         * File parsing strategy: auto selects automatically, fast parses quickly, and quality prioritizes parsing quality
         * @default "auto"
         * @example "auto"
         */
        fileParsingStrategy?: "auto" | "fast" | "quality";
        [key: string]: unknown;
      };
      output: Record<string, unknown>;
    };
    /** Edit images with Tongyi Wanxiang */
    "fusion-api.qwen_image_edit_plus_edit": {
      input: {
        /**
         * Model name
         * @default "qwen-image-edit-plus"
         * @example "qwen-image-edit-plus"
         */
        model?: "qwen-image-edit-max" | "qwen-image-edit-plus" | "qwen-image-edit";
        /**
         * Array of input image URLs, supporting 1 to 3 images
         * @minItems 1
         * @maxItems 3
         * @example ["https://example.com/photo.png"]
         */
        imageURLs: Array<string>;
        /**
         * Editing instruction describing changes to the image
         * @minLength 1
         * @maxLength 800
         * @example "把背景替换为海滩场景"
         */
        prompt: string;
        /**
         * Number of images to generate
         * @minimum 1
         * @maximum 6
         * @default 1
         * @example 1
         */
        generateImageCount?: number;
        /**
         * Negative prompt describing content to avoid
         * @maxLength 500
         * @example "模糊，低画质，畸形"
         */
        negativePrompt?: string;
        size?: string;
        /**
         * Whether to enable intelligent prompt rewriting
         * @default true
         * @example true
         */
        promptExtend?: boolean;
        /**
         * Whether to add a watermark
         * @default false
         * @example false
         */
        watermark?: boolean;
        /**
         * Random seed; fixed seeds can reproduce results
         * @minimum 0
         * @maximum 2147483647
         * @example 42
         */
        seed?: number;
        [key: string]: unknown;
      };
      output: Record<string, unknown>;
    };
    /** Generate images with Tongyi Qianwen */
    "fusion-api.qwen_image_generate": {
      input: {
        /**
         * Model name
         * @default "qwen-image-2.0"
         * @example "qwen-image-2.0"
         */
        model?: "qwen-image-2.0" | "qwen-image-2.0-pro";
        /**
         * Text prompt for image generation
         * @minLength 1
         * @maxLength 800
         * @example "一只在雪地里奔跑的狐狸，电影感，真实摄影"
         */
        prompt: string;
        /**
         * Negative prompt describing content to avoid
         * @maxLength 500
         * @example "低画质，模糊，畸形"
         */
        negativePrompt?: string;
        size?: string;
        /**
         * Number of images to generate, supporting 1 to 6 images
         * @minimum 1
         * @maximum 6
         * @default 1
         * @example 1
         */
        n?: number;
        /**
         * Whether to enable intelligent prompt rewriting
         * @default true
         * @example true
         */
        promptExtend?: boolean;
        /**
         * Whether to add a watermark
         * @default false
         * @example false
         */
        watermark?: boolean;
        /**
         * Random seed; fixed seeds can reproduce results
         * @minimum 0
         * @maximum 2147483647
         * @example 42
         */
        seed?: number;
        [key: string]: unknown;
      };
      output: Array<string>;
    };
    /** Get qwen-mt-image task result */
    "fusion-api.qwen_mt_image_result": {
      input: {
        /**
         * Session ID
         * @example "01936c8e-7890-7abc-def0-123456789abc"
         */
        sessionID: string;
        [key: string]: unknown;
      };
      output: {
        /** Task state. */
        state: "completed";
        /** Task result data. */
        data: Record<string, unknown>;
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "processing";
        /** Task progress. */
        progress: number;
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "not_found";
        /** Error message. */
        error: string;
        [key: string]: unknown;
      };
    };
    /** Get qwen-mt-image task state */
    "fusion-api.qwen_mt_image_state": {
      input: {
        /**
         * Session ID
         * @example "01936c8e-7890-7abc-def0-123456789abc"
         */
        sessionID: string;
        [key: string]: unknown;
      };
      output: {
        /** Task state. */
        state: "completed";
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "processing";
        /** Task progress. */
        progress: number;
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "not_found";
        /** Error message. */
        error: string;
        [key: string]: unknown;
      };
    };
    /** Image machine translation */
    "fusion-api.qwen_mt_image_submit": {
      input: {
        /**
         * Publicly accessible URL of the image to translate
         * @minLength 1
         * @example "https://example.com/menu.jpg"
         */
        imageURL: string;
        /**
         * Source language; auto enables automatic detection
         * @default "auto"
         * @example "auto"
         */
        sourceLang?: "auto" | "zh" | "en" | "ko" | "ja" | "ru" | "es" | "fr" | "pt" | "it" | "de" | "vi";
        /**
         * Target language
         * @example "en"
         */
        targetLang: "zh" | "en" | "ko" | "ja" | "ru" | "es" | "fr" | "pt" | "it" | "vi" | "ms" | "th" | "id" | "ar";
        /**
         * Domain prompt describing the translation style; English is recommended
         * @maxLength 2000
         * @example "E-commerce product description"
         */
        domainHint?: string;
        /**
         * Sensitive word filter list; exact matches are skipped during translation
         * @maxItems 50
         * @example ["LOGO","Brand Name"]
         */
        sensitivities?: Array<string>;
        /**
         * Terminology override list specifying translations for specific words
         * @maxItems 50
         * @example [{"src":"接口","tgt":"API"}]
         */
        terminologies?: Array<{
          /**
           * Source-language term
           * @example "接口"
           */
          src: string;
          /**
           * Target-language term
           * @example "API"
           */
          tgt: string;
          [key: string]: unknown;
        }>;
        /**
         * Whether to skip image subject segmentation and translate all text when skipped
         * @example false
         */
        skipImgSegment?: boolean;
        [key: string]: unknown;
      };
      output: {
        /** Task session ID. */
        sessionId: string;
        [key: string]: unknown;
      };
    };
    /** Generate speech audio */
    "fusion-api.qwen_tts_generate": {
      input: {
        /**
         * Model name.
         * @default "qwen3-tts-flash"
         * @example "qwen3-tts-flash"
         */
        model?: "qwen3-tts-instruct-flash" | "qwen3-tts-flash" | "qwen3-tts-vc-2026-01-22";
        /**
         * Text content to synthesize into speech.
         * @minLength 1
         * @example "你好，欢迎使用千问语音合成服务。"
         */
        text: string;
        /**
         * Preset voice name or cloned voice ID.
         * @minLength 1
         * @default "Cherry"
         * @example "Cherry"
         */
        voice?: string;
        /**
         * Language type of the text.
         * @example "Auto"
         */
        languageType?: "Auto" | "Chinese" | "English" | "German" | "Italian" | "Portuguese" | "Spanish" | "Japanese" | "Korean" | "French" | "Russian";
        /**
         * Speech performance control instruction, only available for instruct models.
         * @minLength 1
         * @example "Speak faster with an upbeat tone."
         */
        instructions?: string;
        /**
         * Whether to optimize speech performance instructions, only available for instruct models.
         * @example true
         */
        optimizeInstructions?: boolean;
        [key: string]: unknown;
      };
      output: {
        /** Temporary URL of the generated audio */
        audioURL: string;
        /** Expiration time of the audio URL */
        expiresAt?: number;
        [key: string]: unknown;
      };
    };
    /** Create a Qwen voice cloning voice and return a preview audio URL. */
    "fusion-api.qwen_voice_cloning_create": {
      input: {
        /**
         * Speech synthesis model that drives the cloned voice.
         * @default "qwen3-tts-vc-2026-01-22"
         * @example "qwen3-tts-vc-2026-01-22"
         */
        targetModel?: "qwen3-tts-vc-realtime-2026-01-15" | "qwen3-tts-vc-realtime-2025-11-27" | "qwen3-tts-vc-2026-01-22";
        /**
         * Short voice name used to identify the cloned voice.
         * @minLength 1
         * @maxLength 16
         * @example "guanyu"
         */
        preferredName: string;
        /**
         * Source audio data for cloning. Use a data URL or a public HTTPS URL.
         * @minLength 1
         * @example "data:audio/mpeg;base64,AAAA"
         */
        audioData: string;
        /**
         * Transcript matching the source audio content.
         * @minLength 1
         * @example "你好，欢迎使用声音复刻服务。"
         */
        text?: string;
        /**
         * Text used to generate the preview audio.
         * @minLength 1
         * @example "你好，欢迎使用声音复刻服务。"
         */
        previewText: string;
        /**
         * Language of the source audio.
         * @example "zh"
         */
        language?: "zh" | "en" | "de" | "it" | "pt" | "es" | "ja" | "ko" | "fr" | "ru";
        [key: string]: unknown;
      };
      output: {
        /** Created cloned voice ID. */
        voiceId: string;
        /** Speech synthesis model that drives the cloned voice. */
        targetModel: "qwen3-tts-vc-realtime-2026-01-15" | "qwen3-tts-vc-realtime-2025-11-27" | "qwen3-tts-vc-2026-01-22";
        /** Temporary URL for the generated preview audio. */
        audioURL: string;
        /** Expiration timestamp for the preview audio URL. */
        expiresAt?: number;
        /** Upstream request ID. */
        requestId: string;
        [key: string]: unknown;
      };
    };
    /** Create a Qwen voice design voice and return preview audio. */
    "fusion-api.qwen_voice_design_create": {
      input: {
        /**
         * Speech synthesis model that drives the designed voice.
         * @default "qwen3-tts-vd-2026-01-26"
         * @example "qwen3-tts-vd-2026-01-26"
         */
        targetModel?: "qwen3-tts-vd-2026-01-26";
        /**
         * Voice description. Only Chinese and English are supported.
         * @minLength 1
         * @maxLength 2048
         * @example "A calm middle-aged male news anchor with a deep magnetic voice and steady pacing."
         */
        voicePrompt: string;
        /**
         * Text used for preview audio.
         * @minLength 1
         * @maxLength 1024
         * @example "各位听众朋友，大家好，欢迎收听晚间新闻。"
         */
        previewText: string;
        /**
         * Short voice name. Only letters, numbers, and underscores are allowed.
         * @minLength 1
         * @maxLength 16
         * @pattern ^[A-Za-z0-9_]+$
         * @example "announcer"
         */
        preferredName: string;
        /**
         * Language tendency used for voice design.
         * @default "zh"
         * @example "zh"
         */
        language?: "zh" | "en" | "de" | "it" | "pt" | "es" | "ja" | "ko" | "fr" | "ru";
        /**
         * Preview audio sample rate.
         * @default 24000
         * @example 24000
         */
        sampleRate?: 8000 | 16000 | 24000 | 48000;
        /**
         * Preview audio format.
         * @default "wav"
         * @example "wav"
         */
        responseFormat?: "pcm" | "wav" | "mp3" | "opus";
        [key: string]: unknown;
      };
      output: {
        /** Created voice name. */
        voice: string;
        /** Speech synthesis model that drives the designed voice. */
        targetModel: "qwen3-tts-vd-2026-01-26";
        /** Preview audio data. */
        previewAudio: {
          /** Base64 encoded preview audio data. */
          data: string;
          /** Preview audio sample rate. */
          sampleRate?: number;
          /** Preview audio format. */
          responseFormat?: "pcm" | "wav" | "mp3" | "opus";
          [key: string]: unknown;
        };
        /** Upstream request ID. */
        requestId: string;
        [key: string]: unknown;
      };
    };
    /** Delete a Qwen voice design voice. */
    "fusion-api.qwen_voice_design_delete": {
      input: {
        /**
         * Voice name.
         * @minLength 1
         * @example "qwen-tts-vd-announcer-voice-20251201102800-a1b2"
         */
        voice: string;
        [key: string]: unknown;
      };
      output: {
        /** Deleted voice name. */
        voice: string;
        /** Upstream request ID. */
        requestId: string;
        [key: string]: unknown;
      };
    };
    /** Generate speech audio using a Qwen voice design voice. */
    "fusion-api.qwen_voice_design_generate": {
      input: {
        /**
         * Text content to synthesize into speech.
         * @minLength 1
         * @example "今天天气怎么样？"
         */
        text: string;
        /**
         * Voice name created by Qwen voice design.
         * @minLength 1
         * @example "qwen-tts-vd-announcer-voice-20251201102800-a1b2"
         */
        voice: string;
        /**
         * Speech synthesis model for the voice design voice.
         * @default "qwen3-tts-vd-2026-01-26"
         * @example "qwen3-tts-vd-2026-01-26"
         */
        model?: "qwen3-tts-vd-2026-01-26";
        [key: string]: unknown;
      };
      output: {
        /** Temporary URL for the generated audio. */
        audioURL: string;
        /** Expiration timestamp for the audio URL. */
        expiresAt?: number;
        /** Upstream request ID. */
        requestId: string;
        [key: string]: unknown;
      };
    };
    /** List Qwen voice design voices. */
    "fusion-api.qwen_voice_design_list": {
      input: {
        /**
         * Page index.
         * @minimum 0
         * @maximum 200
         * @default 0
         * @example 0
         */
        pageIndex?: number;
        /**
         * Number of voices per page.
         * @exclusiveMinimum 0
         * @default 10
         * @example 10
         */
        pageSize?: number;
        [key: string]: unknown;
      };
      output: {
        /** Page index. */
        pageIndex: number;
        /** Number of voices per page. */
        pageSize: number;
        /** Total number of matched voices. */
        totalCount: number;
        /** Voice list. */
        voices: Array<{
          /** Voice name. */
          voice: string;
          /** Speech synthesis model that drives the designed voice. */
          targetModel: "qwen3-tts-vd-2026-01-26";
          /** Language code. */
          language?: "zh" | "en" | "de" | "it" | "pt" | "es" | "ja" | "ko" | "fr" | "ru";
          /** Voice description. */
          voicePrompt?: string;
          /** Preview text. */
          previewText?: string;
          /** Voice creation time. */
          createdAt?: string;
          /** Voice update time. */
          updatedAt?: string;
          [key: string]: unknown;
        }>;
        /** Upstream request ID. */
        requestId: string;
        [key: string]: unknown;
      };
    };
    /** Get details for a Qwen voice design voice. */
    "fusion-api.qwen_voice_design_query": {
      input: {
        /**
         * Voice name.
         * @minLength 1
         * @example "qwen-tts-vd-announcer-voice-20251201102800-a1b2"
         */
        voice: string;
        [key: string]: unknown;
      };
      output: {
        /** Voice name. */
        voice: string;
        /** Speech synthesis model that drives the designed voice. */
        targetModel: "qwen3-tts-vd-2026-01-26";
        /** Language code. */
        language?: "zh" | "en" | "de" | "it" | "pt" | "es" | "ja" | "ko" | "fr" | "ru";
        /** Voice description. */
        voicePrompt?: string;
        /** Preview text. */
        previewText?: string;
        /** Voice creation time. */
        createdAt?: string;
        /** Voice update time. */
        updatedAt?: string;
        /** Upstream request ID. */
        requestId: string;
        [key: string]: unknown;
      };
    };
    /** Query a Seedance video generation task result */
    "fusion-api.seedance_video_result": {
      input: {
        /**
         * Session ID
         * @example "01936c8e-7890-7abc-def0-123456789abc"
         */
        sessionID: string;
        [key: string]: unknown;
      };
      output: {
        /** Task state. */
        state: "completed";
        /** Seedance video generation result data. */
        data: {
          /** Upstream task ID */
          taskId: string;
          /** Model used for the task */
          model: string;
          /** Generated video URL */
          videoURL: string;
          /** Generated last-frame image URL */
          lastFrameURL?: string;
          /** Seed used for this request */
          seed?: number;
          /** Generated video resolution */
          resolution?: "480p" | "720p" | "1080p";
          /** Generated video aspect ratio */
          ratio?: "16:9" | "4:3" | "1:1" | "3:4" | "9:16" | "21:9" | "adaptive";
          /** Generated video duration in seconds */
          duration?: number;
          /** Generated video frame count */
          frames?: number;
          /** Generated video frame rate */
          framesPerSecond?: number;
          /** Whether the generated video includes synchronized audio */
          generateAudio?: boolean;
          /** Tools used by the model */
          tools?: Array<{
            /**
             * Tool type
             * @example "web_search"
             */
            type: "web_search";
            [key: string]: unknown;
          }>;
          /** Unique end-user identifier */
          safetyIdentifier?: string;
          /** Service tier used to process the task */
          serviceTier?: string;
          /** Task expiration threshold in seconds */
          executionExpiresAfter?: number;
          /** Task creation time */
          createdAt?: number;
          /** Task update time */
          updatedAt?: number;
          /** Token usage */
          usage?: {
            /** Token count charged for the output video */
            completionTokens?: number;
            /** Total token count consumed by this request */
            totalTokens?: number;
            /** Tool usage information */
            toolUsage?: {
              /** Number of web search tool calls */
              webSearch?: number;
              [key: string]: unknown;
            };
            [key: string]: unknown;
          };
          [key: string]: unknown;
        };
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "processing";
        /** Task progress. */
        progress: number;
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "not_found";
        /** Error message. */
        error: string;
        [key: string]: unknown;
      };
    };
    /** Get a Seedance video generation task state */
    "fusion-api.seedance_video_state": {
      input: {
        /**
         * Session ID
         * @example "01936c8e-7890-7abc-def0-123456789abc"
         */
        sessionID: string;
        [key: string]: unknown;
      };
      output: {
        /** Task state. */
        state: "completed";
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "processing";
        /** Task progress. */
        progress: number;
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "not_found";
        /** Error message. */
        error: string;
        [key: string]: unknown;
      };
    };
    /** Generate videos with Doubao Seedance */
    "fusion-api.seedance_video_submit": {
      input: {
        /**
         * Video generation model
         * @default "doubao-seedance-2-0-260128"
         * @example "doubao-seedance-2-0-260128"
         */
        model?: "doubao-seedance-2-0-260128" | "doubao-seedance-2-0-fast-260128";
        /**
         * Video generation prompt
         * @minLength 1
         * @maxLength 1000
         * @example "一只小猫在窗边晒太阳，镜头缓慢推进。"
         */
        prompt?: string;
        /**
         * Reference, first-frame, or last-frame images
         * @maxItems 9
         * @default []
         */
        images?: Array<{
          /**
           * Image URL, Base64-encoded data, or asset ID
           * @minLength 1
           * @example "https://example.com/image.png"
           */
          url: string;
          /**
           * Image role
           * @default "first_frame"
           * @example "first_frame"
           */
          role?: "first_frame" | "last_frame" | "reference_image";
          [key: string]: unknown;
        }>;
        /**
         * Reference videos. Only reference_video is supported.
         * @maxItems 3
         * @default []
         */
        videos?: Array<{
          /**
           * Video URL or asset ID
           * @minLength 1
           * @example "https://example.com/video.mp4"
           */
          url: string;
          /**
           * Video role
           * @default "reference_video"
           * @example "reference_video"
           */
          role?: "reference_video";
          [key: string]: unknown;
        }>;
        /**
         * Reference audio files. Only reference_audio is supported.
         * @maxItems 3
         * @default []
         */
        audios?: Array<{
          /**
           * Audio URL, Base64-encoded data, or asset ID
           * @minLength 1
           * @example "https://example.com/audio.mp3"
           */
          url: string;
          /**
           * Audio role
           * @default "reference_audio"
           * @example "reference_audio"
           */
          role?: "reference_audio";
          [key: string]: unknown;
        }>;
        /**
         * Whether to return the generated video's last-frame image
         * @default false
         * @example false
         */
        returnLastFrame?: boolean;
        /**
         * Task expiration threshold in seconds
         * @minimum 3600
         * @maximum 259200
         * @example 172800
         */
        executionExpiresAfter?: number;
        /**
         * Whether the generated video should include synchronized audio
         * @default true
         * @example true
         */
        generateAudio?: boolean;
        /** Tools the model may call */
        tools?: Array<{
          /**
           * Tool type
           * @example "web_search"
           */
          type: "web_search";
          [key: string]: unknown;
        }>;
        /**
         * Unique end-user identifier
         * @minLength 1
         * @maxLength 64
         * @example "user-123"
         */
        safetyIdentifier?: string;
        /**
         * Video resolution
         * @default "720p"
         * @example "720p"
         */
        resolution?: "480p" | "720p" | "1080p";
        /**
         * Generated video aspect ratio
         * @default "adaptive"
         * @example "adaptive"
         */
        ratio?: "16:9" | "4:3" | "1:1" | "3:4" | "9:16" | "21:9" | "adaptive";
        /**
         * Video duration in seconds. Use -1 to let the model choose automatically.
         * @default 5
         * @example 5
         */
        duration?: -1 | number;
        /**
         * Random seed
         * @minimum -1
         * @maximum 4294967295
         * @example 42
         */
        seed?: number;
        /**
         * Whether to add a watermark
         * @default false
         * @example false
         */
        watermark?: boolean;
        [key: string]: unknown;
      };
      output: {
        /** Task session ID. */
        sessionId: string;
        [key: string]: unknown;
      };
    };
    /** Generate illustrations for EPUB content */
    "fusion-api.text_to_epub_illustrate_generate": {
      input: {
        /**
         * Text prompt for image generation
         * @minLength 1
         * @maxLength 1000
         * @example "一只在星空下奔跑的白色独角兽"
         */
        prompt: string;
        /**
         * Reference image URL or Base64 encoding for image-to-image generation
         * @example "https://example.com/reference.jpg"
         */
        image?: string;
        /**
         * Image size, supporting descriptive sizes (1K/2K/4K) or explicit width and height in pixels
         * @default "2048x2048"
         */
        size?: "1K" | "2K" | "4K" | "1k" | "2k" | "4k" | {
          /**
           * Image width in pixels
           * @exclusiveMinimum 0
           * @example 2048
           */
          width: number;
          /**
           * Image height in pixels
           * @exclusiveMinimum 0
           * @example 2048
           */
          height: number;
          [key: string]: unknown;
        };
        /**
         * Whether to enable multi-image generation mode; auto lets the model decide
         * @default "disabled"
         * @example "disabled"
         */
        multiple?: "disabled" | "auto";
        /**
         * Maximum number of images to generate in one request, only effective in multi-image mode
         * @minimum 1
         * @maximum 15
         * @default 1
         * @example 1
         */
        maxCount?: number;
        /**
         * Whether to add a watermark
         * @default true
         * @example true
         */
        watermark?: boolean;
        /**
         * Generation mode: standard prioritizes quality, fast prioritizes speed
         * @default "standard"
         * @example "standard"
         */
        optionsnew?: "standard" | "fast";
        [key: string]: unknown;
      };
      output: Record<string, unknown>;
    };
    /** Compress PNG images with the Tinify API */
    "fusion-api.tinify_png_shrink_compress": {
      input: {
        /**
         * URL of the original image to compress, supporting PNG, JPEG, and WebP formats
         * @minLength 1
         * @example "https://example.com/photo.png"
         */
        imageURL: string;
        [key: string]: unknown;
      };
      output: Record<string, unknown>;
    };
    /** Query first-frame-to-video task result */
    "fusion-api.wanx_i2v_video_result": {
      input: {
        /**
         * Session ID
         * @example "01936c8e-7890-7abc-def0-123456789abc"
         */
        sessionID: string;
        [key: string]: unknown;
      };
      output: {
        /** Upstream task ID */
        taskId: string;
        /** Generated video URL */
        videoURL: string;
        /** Original prompt */
        origPrompt?: string;
        /** Effective prompt */
        actualPrompt?: string;
        /** Billable duration in seconds */
        duration?: number;
        /** Output video duration in seconds */
        outputVideoDuration?: number;
        /** Output video resolution */
        resolution: "720P" | "1080P";
        /** Whether the output video contains audio */
        audio: boolean;
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "processing";
        /** Task progress. */
        progress: number;
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "not_found";
        /** Error message. */
        error: string;
        [key: string]: unknown;
      };
    };
    /** Get wanx-i2v-video task state */
    "fusion-api.wanx_i2v_video_state": {
      input: {
        /**
         * Session ID
         * @example "01936c8e-7890-7abc-def0-123456789abc"
         */
        sessionID: string;
        [key: string]: unknown;
      };
      output: {
        /** Task state. */
        state: "completed";
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "processing";
        /** Task progress. */
        progress: number;
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "not_found";
        /** Error message. */
        error: string;
        [key: string]: unknown;
      };
    };
    /** Generate videos from the first frame with Tongyi Wanxiang */
    "fusion-api.wanx_i2v_video_submit": {
      input: {
        /**
         * Model name
         * @default "wan2.6-i2v-flash"
         * @example "wan2.6-i2v-flash"
         */
        model?: "wan2.6-i2v-flash" | "wan2.6-i2v";
        /**
         * Video generation prompt
         * @minLength 1
         * @maxLength 1500
         * @example "一只橘猫在窗台上伸懒腰，阳光洒满房间"
         */
        prompt?: string;
        /**
         * First-frame image URL or Base64-encoded data
         * @minLength 1
         * @example "https://example.com/first-frame.png"
         */
        imageURL: string;
        /**
         * Negative prompt describing content to avoid
         * @minLength 1
         * @maxLength 500
         * @example "低画质，模糊，抖动"
         */
        negativePrompt?: string;
        /**
         * Whether to generate video with audio; only flash models support disabling audio
         * @default true
         * @example false
         */
        audio?: boolean;
        /**
         * Custom audio file URL, used only when audio is needed
         * @format uri
         * @example "https://example.com/audio.mp3"
         */
        audioURL?: string;
        /**
         * Output video duration in seconds
         * @minimum 2
         * @maximum 15
         * @default 5
         * @example 5
         */
        duration?: number;
        /**
         * Output video resolution
         * @default "1080P"
         * @example "1080P"
         */
        resolution?: "720P" | "1080P";
        /**
         * Whether to enable intelligent prompt rewriting
         * @default true
         * @example true
         */
        promptExtend?: boolean;
        /**
         * Shot type, effective when intelligent prompt rewriting is enabled
         * @example "multi"
         */
        shotType?: "single" | "multi";
        /**
         * Whether to add an AI-generated watermark
         * @default false
         * @example false
         */
        watermark?: boolean;
        /**
         * Random seed; fixed seeds can reproduce results
         * @minimum 0
         * @maximum 2147483647
         * @example 42
         */
        seed?: number;
        [key: string]: unknown;
      };
      output: {
        /** Task session ID. */
        sessionId: string;
        [key: string]: unknown;
      };
    };
    /** Get wanx-image task result */
    "fusion-api.wanx_image_result": {
      input: {
        /**
         * Session ID
         * @example "01936c8e-7890-7abc-def0-123456789abc"
         */
        sessionID: string;
        [key: string]: unknown;
      };
      output: {
        /** Task state. */
        state: "completed";
        /** Task result data. */
        data: Record<string, unknown>;
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "processing";
        /** Task progress. */
        progress: number;
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "not_found";
        /** Error message. */
        error: string;
        [key: string]: unknown;
      };
    };
    /** Get wanx-image task state */
    "fusion-api.wanx_image_state": {
      input: {
        /**
         * Session ID
         * @example "01936c8e-7890-7abc-def0-123456789abc"
         */
        sessionID: string;
        [key: string]: unknown;
      };
      output: {
        /** Task state. */
        state: "completed";
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "processing";
        /** Task progress. */
        progress: number;
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "not_found";
        /** Error message. */
        error: string;
        [key: string]: unknown;
      };
    };
    /** Generate and edit images with Tongyi Wanxiang AI */
    "fusion-api.wanx_image_submit": {
      input: {
        /**
         * Model name
         * @default "wan2.6-image"
         * @example "wan2.6-image"
         */
        model?: "wan2.6-image";
        /**
         * Image generation mode: image-edit for image editing, interleave for mixed text-image layout
         * @default "image-edit"
         * @example "image-edit"
         */
        mode?: "image-edit" | "interleave";
        /**
         * Positive prompt describing the desired generated image content
         * @minLength 1
         * @maxLength 2000
         * @example "生成一只在花园中奔跑的金毛犬"
         */
        prompt: string;
        /**
         * Array of input image URLs; edit mode requires 1-4 images, interleave mode allows 0-1 images
         * @minItems 0
         * @maxItems 4
         * @example ["https://example.com/input.png"]
         */
        imageURLs?: Array<string>;
        /**
         * Negative prompt describing content to avoid
         * @maxLength 500
         * @example "低画质，模糊，畸形"
         */
        negativePrompt?: string;
        size?: string;
        /**
         * Number of images to generate: 1-4 in edit mode, fixed at 1 in interleave mode
         * @minimum 1
         * @maximum 4
         * @default 4
         * @example 1
         */
        n?: number;
        /**
         * Maximum number of generated images in mixed-layout mode, only effective in interleave mode
         * @minimum 1
         * @maximum 5
         * @example 3
         */
        maxImages?: number;
        /**
         * Whether to enable intelligent prompt rewriting, only effective in edit mode
         * @default true
         * @example true
         */
        promptExtend?: boolean;
        /**
         * Whether to add an AI-generated watermark
         * @default false
         * @example false
         */
        watermark?: boolean;
        /**
         * Random seed; fixed seeds can reproduce results
         * @minimum 0
         * @maximum 2147483647
         * @example 42
         */
        seed?: number;
        [key: string]: unknown;
      };
      output: {
        /** Task session ID. */
        sessionId: string;
        [key: string]: unknown;
      };
    };
    /** Get wanx-kf2v-video task result */
    "fusion-api.wanx_kf2v_video_result": {
      input: {
        /**
         * Session ID
         * @example "01936c8e-7890-7abc-def0-123456789abc"
         */
        sessionID: string;
        [key: string]: unknown;
      };
      output: {
        /** Task state. */
        state: "completed";
        /** Task result data. */
        data: Record<string, unknown>;
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "processing";
        /** Task progress. */
        progress: number;
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "not_found";
        /** Error message. */
        error: string;
        [key: string]: unknown;
      };
    };
    /** Get wanx-kf2v-video task state */
    "fusion-api.wanx_kf2v_video_state": {
      input: {
        /**
         * Session ID
         * @example "01936c8e-7890-7abc-def0-123456789abc"
         */
        sessionID: string;
        [key: string]: unknown;
      };
      output: {
        /** Task state. */
        state: "completed";
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "processing";
        /** Task progress. */
        progress: number;
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "not_found";
        /** Error message. */
        error: string;
        [key: string]: unknown;
      };
    };
    /** Generate videos from keyframes with Tongyi Wanxiang */
    "fusion-api.wanx_kf2v_video_submit": {
      input: {
        /**
         * Model name
         * @default "wan2.2-kf2v-flash"
         * @example "wan2.2-kf2v-flash"
         */
        model?: "wan2.2-kf2v-flash" | "wanx2.1-kf2v-plus";
        /**
         * Text prompt describing the video transition process
         * @minLength 1
         * @maxLength 800
         * @example "镜头从平视逐渐上升，展现城市全景"
         */
        prompt?: string;
        /**
         * First-frame image URL, which determines the video aspect ratio
         * @format uri
         * @example "https://example.com/first-frame.png"
         */
        firstFrameURL: string;
        /**
         * Last-frame image URL, used with the first frame to generate a transition video
         * @format uri
         * @example "https://example.com/last-frame.png"
         */
        lastFrameURL?: string;
        /**
         * Negative prompt describing content to avoid
         * @maxLength 500
         * @example "低画质，模糊"
         */
        negativePrompt?: string;
        /**
         * Video effect template name; prompt and last frame are not required when using a template
         * @example "hanfu-1"
         */
        template?: string;
        /**
         * Generated video resolution tier
         * @default "720P"
         * @example "720P"
         */
        resolution?: "480P" | "720P" | "1080P";
        /**
         * Whether to enable intelligent prompt rewriting
         * @default true
         * @example true
         */
        promptExtend?: boolean;
        /**
         * Whether to add a watermark
         * @default false
         * @example false
         */
        watermark?: boolean;
        /**
         * Random seed; fixed seeds can reproduce results
         * @minimum 0
         * @maximum 2147483647
         * @example 42
         */
        seed?: number;
        [key: string]: unknown;
      };
      output: {
        /** Task session ID. */
        sessionId: string;
        [key: string]: unknown;
      };
    };
    /** Query reference-to-video task result */
    "fusion-api.wanx_r2v_video_result": {
      input: {
        /**
         * Session ID
         * @example "01936c8e-7890-7abc-def0-123456789abc"
         */
        sessionID: string;
        [key: string]: unknown;
      };
      output: {
        /** Upstream task ID */
        taskId: string;
        /** Generated video URL */
        videoURL: string;
        /** Original prompt */
        origPrompt?: string;
        /** Total billable duration in seconds */
        duration?: number;
        /** Total input reference video duration in seconds */
        inputVideoDuration?: number;
        /** Output video duration in seconds */
        outputVideoDuration?: number;
        /** Output video resolution */
        size?: "1280*720" | "720*1280" | "960*960" | "1088*832" | "832*1088" | "1920*1080" | "1080*1920" | "1440*1440" | "1632*1248" | "1248*1632";
        /** Output video resolution tier */
        resolution: "720P" | "1080P";
        /** Whether the output video contains audio */
        audio: boolean;
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "processing";
        /** Task progress. */
        progress: number;
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "not_found";
        /** Error message. */
        error: string;
        [key: string]: unknown;
      };
    };
    /** Get wanx-r2v-video task state */
    "fusion-api.wanx_r2v_video_state": {
      input: {
        /**
         * Session ID
         * @example "01936c8e-7890-7abc-def0-123456789abc"
         */
        sessionID: string;
        [key: string]: unknown;
      };
      output: {
        /** Task state. */
        state: "completed";
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "processing";
        /** Task progress. */
        progress: number;
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "not_found";
        /** Error message. */
        error: string;
        [key: string]: unknown;
      };
    };
    /** Generate videos from reference assets with Tongyi Wanxiang */
    "fusion-api.wanx_r2v_video_submit": {
      input: {
        /**
         * Model name
         * @default "wan2.6-r2v-flash"
         * @example "wan2.6-r2v-flash"
         */
        model?: "wan2.6-r2v-flash" | "wan2.6-r2v";
        /**
         * Video generation prompt; use identifiers such as character1 to reference characters
         * @minLength 1
         * @maxLength 1500
         * @example "character1 在咖啡馆里和 character2 开心聊天。"
         */
        prompt: string;
        /**
         * Array of reference image or video URLs, ordered from character1 to characterN
         * @minItems 1
         * @maxItems 5
         * @example ["https://example.com/character1.mp4","https://example.com/character2.png"]
         */
        referenceURLs: Array<string>;
        /**
         * Negative prompt describing content to avoid
         * @minLength 1
         * @maxLength 500
         * @example "低分辨率，错误，最差质量"
         */
        negativePrompt?: string;
        /**
         * Output video resolution; explicit width and height are required
         * @default "1920*1080"
         * @example "1920*1080"
         */
        size?: "1280*720" | "720*1280" | "960*960" | "1088*832" | "832*1088" | "1920*1080" | "1080*1920" | "1440*1440" | "1632*1248" | "1248*1632";
        /**
         * Output video duration in seconds
         * @minimum 2
         * @maximum 10
         * @default 5
         * @example 5
         */
        duration?: number;
        /**
         * Shot type: single for a single shot, multi for multiple shots
         * @example "multi"
         */
        shotType?: "single" | "multi";
        /**
         * Whether to generate video with audio; only flash models support disabling audio
         * @default true
         * @example false
         */
        audio?: boolean;
        /**
         * Whether to add an AI-generated watermark
         * @default false
         * @example false
         */
        watermark?: boolean;
        /**
         * Random seed; fixed seeds can reproduce results
         * @minimum 0
         * @maximum 2147483647
         * @example 42
         */
        seed?: number;
        [key: string]: unknown;
      };
      output: {
        /** Task session ID. */
        sessionId: string;
        [key: string]: unknown;
      };
    };
    /** Query text-to-video task result */
    "fusion-api.wanx_t2v_video_result": {
      input: {
        /**
         * Session ID
         * @example "01936c8e-7890-7abc-def0-123456789abc"
         */
        sessionID: string;
        [key: string]: unknown;
      };
      output: {
        /** Upstream task ID */
        taskId: string;
        /** Generated video URL */
        videoURL: string;
        /** Original prompt */
        origPrompt?: string;
        /** Total billable duration in seconds */
        duration?: number;
        /**
         * Input video duration, fixed at 0 for text-to-video
         * @default 0
         */
        inputVideoDuration?: number;
        /** Output video duration in seconds */
        outputVideoDuration?: number;
        /** Output video resolution */
        size?: "1280*720" | "720*1280" | "960*960" | "1088*832" | "832*1088" | "1920*1080" | "1080*1920" | "1440*1440" | "1632*1248" | "1248*1632";
        /** Output video resolution tier */
        resolution: "720P" | "1080P";
        /** Whether the output video contains audio */
        audio: boolean;
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "processing";
        /** Task progress. */
        progress: number;
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "not_found";
        /** Error message. */
        error: string;
        [key: string]: unknown;
      };
    };
    /** Get wanx-t2v-video task state */
    "fusion-api.wanx_t2v_video_state": {
      input: {
        /**
         * Session ID
         * @example "01936c8e-7890-7abc-def0-123456789abc"
         */
        sessionID: string;
        [key: string]: unknown;
      };
      output: {
        /** Task state. */
        state: "completed";
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "processing";
        /** Task progress. */
        progress: number;
        [key: string]: unknown;
      } | {
        /** Task state. */
        state: "not_found";
        /** Error message. */
        error: string;
        [key: string]: unknown;
      };
    };
    /** Generate text-to-video videos with Tongyi Wanxiang */
    "fusion-api.wanx_t2v_video_submit": {
      input: {
        /**
         * Video generation prompt
         * @minLength 1
         * @maxLength 1500
         * @example "一只橘猫在暖阳下慢慢转头看向镜头，镜头语言自然流畅。"
         */
        prompt: string;
        /**
         * Negative prompt describing content to avoid
         * @minLength 1
         * @maxLength 500
         * @example "低分辨率，错误，最差质量"
         */
        negativePrompt?: string;
        /** @minLength 1 */
        audioURL?: string;
        /**
         * Output video resolution; explicit width and height are required
         * @default "1920*1080"
         * @example "1920*1080"
         */
        size?: "1280*720" | "720*1280" | "960*960" | "1088*832" | "832*1088" | "1920*1080" | "1080*1920" | "1440*1440" | "1632*1248" | "1248*1632";
        /**
         * Output video duration in seconds
         * @minimum 2
         * @maximum 15
         * @default 5
         * @example 5
         */
        duration?: number;
        /**
         * Whether to enable intelligent prompt rewriting
         * @default true
         * @example true
         */
        promptExtend?: boolean;
        /**
         * Shot type: single for a single shot, multi for multiple shots
         * @example "multi"
         */
        shotType?: "single" | "multi";
        /**
         * Whether to add an AI-generated watermark
         * @default false
         * @example false
         */
        watermark?: boolean;
        /**
         * Random seed; fixed seeds can reproduce results
         * @minimum 0
         * @maximum 2147483647
         * @example 42
         */
        seed?: number;
        [key: string]: unknown;
      };
      output: {
        /** Task session ID. */
        sessionId: string;
        [key: string]: unknown;
      };
    };
  }
}
