import "@oomol-lab/connector";

declare module "@oomol-lab/connector" {
  interface ActionRegistry {
    /** Detect whether a plain text document was generated by AI with GPTZero and return document, paragraph, and sentence-level scores. */
    "gptzero.detect_text": {
      input: {
        /**
         * The plain text document to analyze.
         * @minLength 1
         */
        document: string;
        /**
         * Optional GPTZero API/model version to request.
         * @minLength 1
         */
        version?: string;
      };
      output: {
        /** The GPTZero API/model version returned for the response. */
        version: string | null;
        /** The GPTZero scan ID when returned by the API. */
        scanId: string | null;
        /** Normalized GPTZero document results. */
        documents: Array<{
          /** The GPTZero document ID when returned by the API. */
          documentId: string | null;
          /** The GPTZero model or API version used for this document. */
          version: string | null;
          /** GPTZero's document classification, such as HUMAN_ONLY, MIXED, or AI_ONLY. */
          classification: string | null;
          /** GPTZero's human-readable result message. */
          resultMessage: string | null;
          /**
           * A probability score between 0 and 1 when GPTZero returns the value.
           * @minimum 0
           * @maximum 1
           */
          averageGeneratedProbability: number | null;
          /**
           * A probability score between 0 and 1 when GPTZero returns the value.
           * @minimum 0
           * @maximum 1
           */
          completelyGeneratedProbability: number | null;
          /** The document burstiness score returned by GPTZero. */
          overallBurstiness: number | null;
          /** GPTZero class probability fields such as ai, human, and mixed. */
          classProbabilities: Record<string, unknown> | null;
          /** GPTZero's confidence category when returned. */
          confidenceCategory: string | null;
          /**
           * A probability score between 0 and 1 when GPTZero returns the value.
           * @minimum 0
           * @maximum 1
           */
          confidenceScore: number | null;
          /** GPTZero confidence score details when returned by the API. */
          confidenceScoresRaw: Record<string, unknown> | null;
          /** GPTZero writing statistics when returned. */
          writingStats: Record<string, unknown> | null;
          /** Paragraph-level GPTZero results. */
          paragraphs: Array<{
            /**
             * A probability score between 0 and 1 when GPTZero returns the value.
             * @minimum 0
             * @maximum 1
             */
            completelyGeneratedProbability: number | null;
            /** The number of sentences GPTZero grouped into this paragraph. */
            sentenceCount: number | null;
            /** The index of the first sentence in this paragraph group. */
            startSentenceIndex: number | null;
            /** The raw GPTZero object for forward-compatible fields. */
            raw: Record<string, unknown>;
          }>;
          /** Sentence-level GPTZero results. */
          sentences: Array<{
            /** The sentence text returned by GPTZero. */
            sentence: string | null;
            /**
             * A probability score between 0 and 1 when GPTZero returns the value.
             * @minimum 0
             * @maximum 1
             */
            generatedProbability: number | null;
            /** The perplexity score returned by GPTZero. */
            perplexity: number | null;
            /** Whether GPTZero highlighted this sentence as likely AI-generated. */
            highlightedForAi: boolean | null;
            /** The raw GPTZero object for forward-compatible fields. */
            raw: Record<string, unknown>;
          }>;
          /** The raw GPTZero object for forward-compatible fields. */
          raw: Record<string, unknown>;
        }>;
        /** The raw GPTZero object for forward-compatible fields. */
        raw: Record<string, unknown>;
      };
    };
  }
}
