import "@oomol-lab/connector";

declare module "@oomol-lab/connector" {
  interface ActionRegistry {
    /** Compress a PDF URL and return the generated compressed PDF file URL. */
    "pdf_co.compress_pdf": {
      input: {
        /**
         * Publicly reachable source document URL.
         * @format uri
         */
        url: string;
        /**
         * Optional output file name generated by PDF.co.
         * @minLength 1
         */
        name?: string;
        /** Optional PDF.co compression configuration object. */
        config?: Record<string, unknown>;
      };
      output: {
        /**
         * The generated output file URL returned by PDF.co.
         * @format uri
         */
        url: string | null;
        /** Inline response body returned by PDF.co when inline mode is used. */
        body: unknown;
        /** The PDF.co job identifier when returned. */
        jobId: string | null;
        /** The number of credits used by the operation when returned. */
        credits: number | null;
        /** The number of remaining account credits after the operation when returned. */
        remainingCredits: number | null;
        /** The operation duration in milliseconds when returned. */
        duration: number | null;
        /** The upstream PDF.co status string when returned. */
        status: string | null;
        /** The upstream PDF.co message when returned. */
        message: string | null;
        /** The raw PDF.co JSON response for fields not normalized by the connector. */
        raw: Record<string, unknown>;
      };
    };
    /** Get the current PDF.co account credit balance for the API key. */
    "pdf_co.get_account_balance": {
      input: Record<string, never>;
      output: {
        /** The account credit balance returned by PDF.co. */
        credits: number | null;
        /** The upstream PDF.co status string when returned. */
        status: string | null;
        /** The upstream PDF.co message when returned. */
        message: string | null;
        /** The raw PDF.co JSON response. */
        raw: Record<string, unknown>;
      };
    };
    /** Read metadata, page information, and security details from a PDF URL. */
    "pdf_co.get_pdf_info": {
      input: {
        /**
         * Publicly reachable source document URL.
         * @format uri
         */
        url: string;
        /**
         * Optional password for encrypted source PDF files.
         * @minLength 1
         */
        password?: string;
        /** Optional PDF.co operation timeout in seconds. */
        timeout?: number;
        /** Optional output link expiration time in minutes, subject to the account plan limits. */
        expiration?: number;
        /** Advanced PDF.co profiles object forwarded to the endpoint as-is. */
        profiles?: Record<string, unknown>;
        /**
         * Optional HTTP username for protected source URLs.
         * @minLength 1
         */
        httpUsername?: string;
        /**
         * Optional HTTP password for protected source URLs.
         * @minLength 1
         */
        httpPassword?: string;
      };
      output: {
        /** The number of pages in the source PDF when returned. */
        pageCount: number | null;
        /** The PDF title metadata when returned. */
        title: string | null;
        /** The PDF author metadata when returned. */
        author: string | null;
        /** The PDF subject metadata when returned. */
        subject: string | null;
        /** The PDF keyword metadata when returned. */
        keywords: string | null;
        /** Whether PDF.co reported the source PDF as encrypted. */
        encrypted: boolean | null;
        /** The number of credits used by the operation when returned. */
        credits: number | null;
        /** The number of remaining account credits after the operation when returned. */
        remainingCredits: number | null;
        /** The operation duration in milliseconds when returned. */
        duration: number | null;
        /** The upstream PDF.co status string when returned. */
        status: string | null;
        /** The upstream PDF.co message when returned. */
        message: string | null;
        /** The raw PDF.co JSON response for fields not normalized by the connector. */
        raw: Record<string, unknown>;
      };
    };
    /** Convert raw HTML into a PDF document and return the generated file URL. */
    "pdf_co.html_to_pdf": {
      input: {
        /**
         * The raw HTML markup to render as a PDF.
         * @minLength 1
         */
        html: string;
        /**
         * Optional PDF.co HTML template identifier.
         * @minLength 1
         */
        templateId?: string;
        /** Optional data object used with a PDF.co HTML template. */
        templateData?: Record<string, unknown>;
        /**
         * Optional output file name generated by PDF.co.
         * @minLength 1
         */
        name?: string;
        /**
         * Custom PDF margins such as '10px 10px 10px 10px' or a single value such as '5mm'.
         * @minLength 1
         */
        margins?: string;
        /**
         * Paper size such as Letter, A4, or a custom width and height.
         * @minLength 1
         */
        paperSize?: string;
        /** PDF page orientation. */
        orientation?: "Portrait" | "Landscape";
        /** Whether background graphics should be printed into the PDF. */
        printBackground?: boolean;
        /** CSS media type used while rendering the HTML or URL. */
        mediaType?: "print" | "screen";
        /** Whether PDF.co should skip waiting for full page load. */
        doNotWaitFullLoad?: boolean;
        /**
         * Optional HTML header inserted into the rendered PDF.
         * @minLength 1
         */
        header?: string;
        /**
         * Optional HTML footer inserted into the rendered PDF.
         * @minLength 1
         */
        footer?: string;
        /** Optional render timeout in milliseconds. */
        renderTimeout?: number;
        /** Optional output link expiration time in minutes, subject to the account plan limits. */
        expiration?: number;
        /** Advanced PDF.co profiles object forwarded to the endpoint as-is. */
        profiles?: Record<string, unknown>;
        /**
         * Optional custom JavaScript executed during rendering.
         * @minLength 1
         */
        customScript?: string;
      };
      output: {
        /**
         * The generated output file URL returned by PDF.co.
         * @format uri
         */
        url: string | null;
        /** Inline response body returned by PDF.co when inline mode is used. */
        body: unknown;
        /** The PDF.co job identifier when returned. */
        jobId: string | null;
        /** The number of credits used by the operation when returned. */
        credits: number | null;
        /** The number of remaining account credits after the operation when returned. */
        remainingCredits: number | null;
        /** The operation duration in milliseconds when returned. */
        duration: number | null;
        /** The upstream PDF.co status string when returned. */
        status: string | null;
        /** The upstream PDF.co message when returned. */
        message: string | null;
        /** The raw PDF.co JSON response for fields not normalized by the connector. */
        raw: Record<string, unknown>;
      };
    };
    /** Merge multiple PDF URLs into one PDF document. */
    "pdf_co.merge_pdfs": {
      input: {
        /**
         * The source PDF URLs to merge in order.
         * @minItems 2
         */
        urls: Array<string>;
        /**
         * Optional output file name generated by PDF.co.
         * @minLength 1
         */
        name?: string;
        /** Optional PDF.co operation timeout in seconds. */
        timeout?: number;
        /** Optional output link expiration time in minutes, subject to the account plan limits. */
        expiration?: number;
        /** Advanced PDF.co profiles object forwarded to the endpoint as-is. */
        profiles?: Record<string, unknown>;
        /**
         * Optional HTTP username for protected source URLs.
         * @minLength 1
         */
        httpUsername?: string;
        /**
         * Optional HTTP password for protected source URLs.
         * @minLength 1
         */
        httpPassword?: string;
      };
      output: {
        /**
         * The generated output file URL returned by PDF.co.
         * @format uri
         */
        url: string | null;
        /** Inline response body returned by PDF.co when inline mode is used. */
        body: unknown;
        /** The PDF.co job identifier when returned. */
        jobId: string | null;
        /** The number of credits used by the operation when returned. */
        credits: number | null;
        /** The number of remaining account credits after the operation when returned. */
        remainingCredits: number | null;
        /** The operation duration in milliseconds when returned. */
        duration: number | null;
        /** The upstream PDF.co status string when returned. */
        status: string | null;
        /** The upstream PDF.co message when returned. */
        message: string | null;
        /** The raw PDF.co JSON response for fields not normalized by the connector. */
        raw: Record<string, unknown>;
      };
    };
    /** Convert a PDF URL to text and return either a file URL or inline text payload. */
    "pdf_co.pdf_to_text": {
      input: {
        /**
         * Publicly reachable source document URL.
         * @format uri
         */
        url: string;
        /**
         * Zero-based page indexes or ranges, such as '0,2,5-10'.
         * @minLength 1
         */
        pages?: string;
        /**
         * OCR language code such as eng.
         * @minLength 1
         */
        lang?: string;
        /** Whether PDF.co should return extracted text inside the JSON response. */
        inline?: boolean;
        /** Whether PDF.co should unwrap text lines. */
        unwrap?: boolean;
        /** Whether PDF.co should group nearby text lines. */
        lineGrouping?: boolean;
        /**
         * Optional extraction rectangle in PDF.co coordinate format.
         * @minLength 1
         */
        rect?: string;
        /**
         * Optional output file name generated by PDF.co.
         * @minLength 1
         */
        name?: string;
        /**
         * Optional password for encrypted source PDF files.
         * @minLength 1
         */
        password?: string;
        /** Optional PDF.co operation timeout in seconds. */
        timeout?: number;
        /** Optional output link expiration time in minutes, subject to the account plan limits. */
        expiration?: number;
        /** Advanced PDF.co profiles object forwarded to the endpoint as-is. */
        profiles?: Record<string, unknown>;
        /**
         * Optional HTTP username for protected source URLs.
         * @minLength 1
         */
        httpUsername?: string;
        /**
         * Optional HTTP password for protected source URLs.
         * @minLength 1
         */
        httpPassword?: string;
      };
      output: {
        /**
         * The generated output file URL returned by PDF.co.
         * @format uri
         */
        url: string | null;
        /** Inline response body returned by PDF.co when inline mode is used. */
        body: unknown;
        /** The PDF.co job identifier when returned. */
        jobId: string | null;
        /** The number of credits used by the operation when returned. */
        credits: number | null;
        /** The number of remaining account credits after the operation when returned. */
        remainingCredits: number | null;
        /** The operation duration in milliseconds when returned. */
        duration: number | null;
        /** The upstream PDF.co status string when returned. */
        status: string | null;
        /** The upstream PDF.co message when returned. */
        message: string | null;
        /** The raw PDF.co JSON response for fields not normalized by the connector. */
        raw: Record<string, unknown>;
      };
    };
    /** Split a PDF URL into one or more output files by page numbers or ranges. */
    "pdf_co.split_pdf": {
      input: {
        /**
         * Publicly reachable source document URL.
         * @format uri
         */
        url: string;
        /**
         * One-based page indexes or ranges, such as '1,2,3-7' or '!1' for the last page.
         * @minLength 1
         */
        pages?: string;
        /** Whether PDF.co should return results inside the JSON response. */
        inline?: boolean;
        /**
         * Optional output file name generated by PDF.co.
         * @minLength 1
         */
        name?: string;
        /**
         * Optional password for encrypted source PDF files.
         * @minLength 1
         */
        password?: string;
        /** Optional PDF.co operation timeout in seconds. */
        timeout?: number;
        /** Optional output link expiration time in minutes, subject to the account plan limits. */
        expiration?: number;
        /** Advanced PDF.co profiles object forwarded to the endpoint as-is. */
        profiles?: Record<string, unknown>;
        /**
         * Optional HTTP username for protected source URLs.
         * @minLength 1
         */
        httpUsername?: string;
        /**
         * Optional HTTP password for protected source URLs.
         * @minLength 1
         */
        httpPassword?: string;
      };
      output: {
        /**
         * The generated output file URL returned by PDF.co.
         * @format uri
         */
        url: string | null;
        /** Inline response body returned by PDF.co when inline mode is used. */
        body: unknown;
        /** The PDF.co job identifier when returned. */
        jobId: string | null;
        /** The number of credits used by the operation when returned. */
        credits: number | null;
        /** The number of remaining account credits after the operation when returned. */
        remainingCredits: number | null;
        /** The operation duration in milliseconds when returned. */
        duration: number | null;
        /** The upstream PDF.co status string when returned. */
        status: string | null;
        /** The upstream PDF.co message when returned. */
        message: string | null;
        /** The raw PDF.co JSON response for fields not normalized by the connector. */
        raw: Record<string, unknown>;
      };
    };
    /** Convert a publicly reachable web page URL into a PDF document. */
    "pdf_co.url_to_pdf": {
      input: {
        /**
         * The publicly reachable web page URL to render.
         * @format uri
         */
        url: string;
        /**
         * Optional output file name generated by PDF.co.
         * @minLength 1
         */
        name?: string;
        /**
         * Custom PDF margins such as '10px 10px 10px 10px' or a single value such as '5mm'.
         * @minLength 1
         */
        margins?: string;
        /**
         * Paper size such as Letter, A4, or a custom width and height.
         * @minLength 1
         */
        paperSize?: string;
        /** PDF page orientation. */
        orientation?: "Portrait" | "Landscape";
        /** Whether background graphics should be printed into the PDF. */
        printBackground?: boolean;
        /** CSS media type used while rendering the HTML or URL. */
        mediaType?: "print" | "screen";
        /** Whether PDF.co should skip waiting for full page load. */
        doNotWaitFullLoad?: boolean;
        /**
         * Optional HTML header inserted into the rendered PDF.
         * @minLength 1
         */
        header?: string;
        /**
         * Optional HTML footer inserted into the rendered PDF.
         * @minLength 1
         */
        footer?: string;
        /** Optional render timeout in milliseconds. */
        renderTimeout?: number;
        /** Optional output link expiration time in minutes, subject to the account plan limits. */
        expiration?: number;
        /** Advanced PDF.co profiles object forwarded to the endpoint as-is. */
        profiles?: Record<string, unknown>;
        /**
         * Optional custom JavaScript executed during rendering.
         * @minLength 1
         */
        customScript?: string;
        /** Optional template data object forwarded to PDF.co. */
        templateData?: Record<string, unknown>;
        /**
         * Optional HTTP username for protected source URLs.
         * @minLength 1
         */
        httpUsername?: string;
        /**
         * Optional HTTP password for protected source URLs.
         * @minLength 1
         */
        httpPassword?: string;
      };
      output: {
        /**
         * The generated output file URL returned by PDF.co.
         * @format uri
         */
        url: string | null;
        /** Inline response body returned by PDF.co when inline mode is used. */
        body: unknown;
        /** The PDF.co job identifier when returned. */
        jobId: string | null;
        /** The number of credits used by the operation when returned. */
        credits: number | null;
        /** The number of remaining account credits after the operation when returned. */
        remainingCredits: number | null;
        /** The operation duration in milliseconds when returned. */
        duration: number | null;
        /** The upstream PDF.co status string when returned. */
        status: string | null;
        /** The upstream PDF.co message when returned. */
        message: string | null;
        /** The raw PDF.co JSON response for fields not normalized by the connector. */
        raw: Record<string, unknown>;
      };
    };
  }
}
