import "@oomol-lab/connector";

declare module "@oomol-lab/connector" {
  interface ActionRegistry {
    /** Get sharing, referral, and reward statistics for one Referral Rock member. */
    "referralrock.get_member_stats": {
      input: {
        /**
         * The member email address, internal ID, external ID, or referral code to look up.
         * @minLength 1
         */
        query: string;
        /** The duration over which to calculate member statistics. */
        timePeriod: "All" | "MonthToDate" | "LastMonth" | "Last7Days" | "Last30Days";
      };
      output: {
        /** The member's total views. */
        memberViews?: number;
        /** The number of times the member shared a link. */
        memberShares?: number;
        /** The number of referrals attributed to the member. */
        referralsCount?: number;
        /** The number of approved referrals. */
        referralsApproved?: number;
        /** The number of qualified referrals. */
        referralsQualified?: number;
        /** The number of pending referrals. */
        referralsPending?: number;
        /** The total referral views. */
        referralsViews?: number;
        /** The number of rewards generated by the member. */
        rewardsCount?: number;
        [key: string]: unknown;
      };
    };
    /** List and search members across Referral Rock referral programs. */
    "referralrock.list_members": {
      input: {
        /** The program ID, name, or title by which to filter members. */
        programId?: string;
        /** A member email address, internal ID, external ID, or referral code to search for. */
        query?: string;
        /** Whether to return disabled members instead of active members. */
        showDisabled?: boolean;
        /** The documented member sort order. */
        sort?: "Member_Views_Desc" | "Member_Views_Asc" | "Page_Views_Desc" | "Page_Views_Asc" | "Lead_Count_Desc" | "Lead_Count_Asc" | "Reward_Issued_Total_Desc" | "Reward_Issued_Total_Asc" | "Member_Full_Name_Desc" | "Member_Full_Name_Asc" | "Create_Dt_Desc" | "Create_Dt_Asc";
        /**
         * Return members created on or after this date.
         * @format date
         */
        dateFrom?: string;
        /**
         * Return members created on or before this date.
         * @format date
         */
        dateTo?: string;
        /**
         * The zero-based index at which to start returning records.
         * @minimum 0
         */
        offset?: number;
        /**
         * The maximum number of records to return.
         * @minimum 1
         */
        count?: number;
      };
      output: {
        /** The members returned by Referral Rock. */
        members: Array<Record<string, unknown>>;
        /** The zero-based offset returned by Referral Rock. */
        offset: number;
        /** The total number of matching records. */
        total: number;
        /** Additional information returned by Referral Rock. */
        message?: string;
      };
    };
    /** List referral programs in the connected Referral Rock account. */
    "referralrock.list_programs": {
      input: {
        /** The ID of a specific referral program to return. */
        programId?: string;
        /**
         * The zero-based index at which to start returning records.
         * @minimum 0
         */
        offset?: number;
        /**
         * The maximum number of records to return.
         * @minimum 1
         */
        count?: number;
      };
      output: {
        /** The programs returned by Referral Rock. */
        programs: Array<Record<string, unknown>>;
        /** The zero-based offset returned by Referral Rock. */
        offset: number;
        /** The total number of matching records. */
        total: number;
        /** Additional information returned by Referral Rock. */
        message?: string;
      };
    };
    /** List and search referrals in the connected Referral Rock account. */
    "referralrock.list_referrals": {
      input: {
        /** The program ID, name, or title by which to filter referrals. */
        programId?: string;
        /** A referral email address, internal ID, external ID, or referral code to search for. */
        query?: string;
        /** The referring member ID by which to filter referrals. */
        memberId?: string;
        /** The documented referral sort order. */
        sort?: "Create_Dt_Desc" | "Create_Dt_Asc" | "Amount_Desc" | "Amount_Asc" | "Qualified_Dt_Desc" | "Qualified_Dt_Asc" | "Closed_Dt_Desc" | "Closed_Dt_Asc";
        /**
         * Return referrals created on or after this date.
         * @format date
         */
        dateFrom?: string;
        /**
         * Return referrals created on or before this date.
         * @format date
         */
        dateTo?: string;
        /** The referral status by which to filter results. */
        status?: "pending" | "qualified" | "approved" | "denied";
        /**
         * The zero-based index at which to start returning records.
         * @minimum 0
         */
        offset?: number;
        /**
         * The maximum number of records to return.
         * @minimum 1
         */
        count?: number;
      };
      output: {
        /** The referrals returned by Referral Rock. */
        referrals: Array<Record<string, unknown>>;
        /** The zero-based offset returned by Referral Rock. */
        offset: number;
        /** The total number of matching records. */
        total: number;
        /** Additional information returned by Referral Rock. */
        message?: string;
      };
    };
  }
}
